'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createHash}=require('node:crypto');
const {createPdvRuntime}=require('../js/core/pdv-runtime');
const {COMMERCIAL_MEDIA_SCHEMA_VERSION}=require('../js/core/database/commercial-media-migrations');
const {createProductPhotoClient}=require('../desktop/product-photo-bridge.cjs');

const PNG_1PX=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'artisys-commercial-'));let timestamp='2026-09-15T12:00:00.000Z';let sequence=0;const runtime=createPdvRuntime({dbPath:path.join(dir,'pdv.sqlite'),productPhotoDir:path.join(dir,'photos'),now:()=>timestamp,idFactory:prefix=>`${prefix}-${++sequence}`});runtime.catalog.createUser({id:'admin1',username:'admin',name:'Admin',role:'admin',password:'senha-admin-123'});runtime.catalog.createUser({id:'seller1',username:'maria',name:'Maria',role:'cashier',password:'senha-maria-123'});runtime.catalog.upsertProduct({id:'p1',name:'Produto',salePriceCents:1000,trackStock:false});return{runtime,dir,setNow:value=>{timestamp=value;},close(){runtime.close();fs.rmSync(dir,{recursive:true,force:true});}};}

test('schema v12 adds commission snapshots, ledger and file-only photo metadata without deleting data',()=>{const ctx=fixture();try{assert.equal(ctx.runtime.db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version,COMMERCIAL_MEDIA_SCHEMA_VERSION);const columns=new Set(ctx.runtime.db.prepare('PRAGMA table_info(sale_items)').all().map(row=>row.name));for(const name of ['commission_bps_snapshot','commission_base_cents','commission_cents'])assert.equal(columns.has(name),true);for(const table of ['seller_commission_rules','commission_ledger','commission_payments','product_photos'])assert.ok(ctx.runtime.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table));assert.equal(ctx.runtime.catalog.getProduct('p1').name,'Produto');}finally{ctx.close();}});

test('commission snapshots net item value and records payment, return restore and sale cancellation',()=>{const ctx=fixture();try{const {runtime}=ctx;runtime.commissions.upsertRule({sellerId:'seller1',commissionBps:1000},{userId:'admin1',role:'admin'});runtime.commissions.upsertRule({sellerId:'seller1',productId:'p1',commissionBps:1200},{userId:'admin1',role:'admin'});runtime.commissions.upsertRule({sellerId:'seller1',productId:'p1',commissionBps:1000},{userId:'admin1',role:'admin'});runtime.sales.openSale({id:'s1',saleNumber:'1',terminalId:'T1',operatorId:'admin1',sellerId:'seller1'});runtime.sales.addItem('s1',{productId:'p1',quantity:2});runtime.sales.applyDiscount('s1',{discountCents:200});const completed=runtime.sales.completeSale('s1',{payments:[{method:'CASH',amountCents:1800}],actor:{userId:'admin1',role:'admin',terminalId:'T1'}});assert.equal(completed.items[0].commissionBpsSnapshot,1000);assert.equal(completed.items[0].commissionBaseCents,1800);assert.equal(completed.items[0].commissionCents,180);runtime.commissions.pay({sellerId:'seller1',amountCents:80,periodFrom:'2026-09-01',periodTo:'2026-09-30'},{userId:'admin1',role:'admin'});const ret=runtime.returns.createReturn({id:'r1',saleId:'s1',terminalId:'T1',operatorId:'admin1',items:[{saleItemId:completed.items[0].id,quantity:1}],refunds:[{method:'CASH',amountCents:1000}],reason:'Troca',actor:{userId:'admin1',role:'admin'}});assert.equal(runtime.commissions.outstanding('seller1'),10);runtime.returns.cancelReturn(ret.id,{reason:'Devolucao desfeita',actor:{userId:'admin1',role:'admin'}});assert.equal(runtime.commissions.outstanding('seller1'),100);runtime.sales.cancelSale('s1',{reason:'Venda cancelada',actor:{userId:'admin1',role:'admin'}});assert.equal(runtime.commissions.outstanding('seller1'),-80);const report=runtime.commissions.report({sellerId:'seller1'});assert.equal(report.sellers[0].earnedCents,180);assert.equal(report.sellers[0].paidCents,80);assert.equal(report.sellers[0].reversedCents,180);const sales=runtime.reports.buildSalesSummary({from:'2026-09-15T00:00:00Z',to:'2026-09-15T23:59:59Z',sellerId:'seller1'});assert.equal(sales.cancelledSalesCount,1);assert.equal(sales.cancelledSalesCents,1800);}finally{ctx.close();}});

test('product photos persist only relative paths and hashes, serve variants and retain deletion for 30 days',()=>{const ctx=fixture();try{const {runtime}=ctx;const photo=runtime.productPhotos.save({productId:'p1',mimeType:'image/png',originalBase64:PNG_1PX.toString('base64'),thumbnailBase64:PNG_1PX.toString('base64')},{userId:'admin1',role:'admin'});assert.match(photo.originalPath,/^originals\/[a-f0-9]{64}\.png$/);assert.match(photo.thumbnailPath,/^thumbnails\/[a-f0-9]{64}\.png$/);assert.equal(JSON.stringify(runtime.db.prepare('SELECT * FROM product_photos').get()).includes(PNG_1PX.toString('base64')),false);assert.deepEqual(runtime.productPhotos.read('p1','thumbnail').bytes,PNG_1PX);assert.equal(runtime.catalog.getProduct('p1').photo.thumbnailSha256,photo.thumbnailSha256);const removed=runtime.productPhotos.remove('p1',{userId:'admin1',role:'admin'});assert.ok(removed.deletedAt);assert.equal(runtime.productPhotos.get('p1'),null);assert.equal(fs.existsSync(path.join(ctx.dir,'photos',photo.originalPath)),true);ctx.setNow('2026-10-16T12:00:00.000Z');assert.equal(runtime.productPhotos.cleanupExpired().removedRecords,1);assert.equal(fs.existsSync(path.join(ctx.dir,'photos',photo.originalPath)),false);}finally{ctx.close();}});

test('terminal photo sync downloads only missing thumbnails once per day and fetches original on demand',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'artisys-photo-cache-'));try{const hash=createHash('sha256').update(PNG_1PX).digest('hex');const photo={productId:'p1',version:1,mimeType:'image/png',originalSha256:hash,thumbnailSha256:hash,deletedAt:null};const calls=[];const fetchImpl=async url=>{calls.push(url);if(url.endsWith('/manifest'))return{ok:true,status:200,text:async()=>JSON.stringify([photo])};return{ok:true,status:200,arrayBuffer:async()=>PNG_1PX};};const client=createProductPhotoClient({cacheDir:dir,fetchImpl,getApiBase:()=> 'http://server',now:()=>new Date('2026-09-15T08:00:00Z')});client.startSync('token');for(let index=0;index<50&&client.status().running;index+=1)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(client.status().failed,0);assert.equal(calls.filter(url=>url.endsWith('/thumbnail')).length,1);assert.equal(calls.some(url=>url.endsWith('/original')),false);const count=calls.length;client.startSync('token');await new Promise(resolve=>setTimeout(resolve,10));assert.equal(calls.length,count);const source=await client.dataUrl('p1','token',{variant:'original'});assert.match(source,/^data:image\/png;base64,/);assert.equal(calls.filter(url=>url.endsWith('/original')).length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('terminal photo sync retries an interrupted same-day download and resumes only the missing file',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'artisys-photo-retry-'));try{const hash=createHash('sha256').update(PNG_1PX).digest('hex');const photo={productId:'p1',version:1,mimeType:'image/png',originalSha256:hash,thumbnailSha256:hash,deletedAt:null};let thumbnailAttempts=0;const fetchImpl=async url=>{if(url.endsWith('/manifest'))return{ok:true,status:200,text:async()=>JSON.stringify([photo])};thumbnailAttempts+=1;return{ok:true,status:200,arrayBuffer:async()=>thumbnailAttempts===1?Buffer.from('download interrompido'):PNG_1PX};};const client=createProductPhotoClient({cacheDir:dir,fetchImpl,getApiBase:()=> 'http://server',now:()=>new Date('2026-09-15T08:00:00Z')});client.startSync('token');for(let index=0;index<50&&client.status().running;index+=1)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(client.status().failed,1);assert.equal(client.status().lastCompletedAt,null);client.startSync('token');for(let index=0;index<50&&client.status().running;index+=1)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(client.status().failed,0);assert.ok(client.status().lastCompletedAt);assert.equal(thumbnailAttempts,2);const source=await client.dataUrl('p1','token');assert.match(source,/^data:image\/png;base64,/);assert.equal(thumbnailAttempts,2);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
