'use strict';

const test=require('node:test');const assert=require('node:assert/strict');
const {createFiscalSidecar}=require('../server/fiscal-sidecar');
const {createControlledFiscalAdapter}=require('../server/fiscal-sidecar/controlled-adapter');
const {createAcbrLocalProvider}=require('../js/domains/fiscal/acbr-local-provider');
const {sanitizeText,sanitizeValue,assertProductionAdapterMode,normalizeAuthToken}=require('../js/domains/fiscal/security-hardening');
const {buildSidecarEnv,detectProductionRuntime}=require('../desktop/fiscal-sidecar-runtime.cjs');
const TOKEN='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGH';const WRONG_TOKEN='wrong-token-0123456789abcdefghijklmnopqrstuvwxyz';const bearer=(token=TOKEN)=>({authorization:`Bearer ${token}`});
function adapter(overrides={}){return{status:async()=>({ok:true,status:200,data:{ready:true},error:null}),issue:async input=>({ok:true,status:200,data:input,error:null}),query:async input=>({ok:true,status:200,data:input,error:null}),cancel:async input=>({ok:true,status:200,data:input,error:null}),...overrides};}

test('P24 redacts bearer tokens and named fiscal secrets from strings and objects',()=>{const text=sanitizeText(`Authorization: Bearer ${TOKEN} password=hunter2 csc=CSC-SECRET pfxBase64=ABCDEF`);assert.doesNotMatch(text,new RegExp(TOKEN));assert.doesNotMatch(text,/hunter2|CSC-SECRET|ABCDEF/);assert.match(text,/\[REDACTED\]/);const value=sanitizeValue({token:TOKEN,password:'hunter2',nested:{csc:'CSC-SECRET',safe:'ok'}});assert.equal(value.token,'[REDACTED]');assert.equal(value.password,'[REDACTED]');assert.equal(value.nested.csc,'[REDACTED]');assert.equal(value.nested.safe,'ok');});
test('P24 validates strong ephemeral sidecar tokens',()=>{assert.equal(normalizeAuthToken(TOKEN),TOKEN);assert.throws(()=>normalizeAuthToken('short-token'),/token/i);assert.throws(()=>normalizeAuthToken(`${TOKEN} with-space`),/token/i);});
test('P24 blocks controlled mock adapters in production and allows unconfigured fail-closed mode',()=>{assert.throws(()=>assertProductionAdapterMode('mock-success',{production:true}),/mock.*produc/i);assert.throws(()=>createControlledFiscalAdapter({mode:'mock-failure',production:true}),/mock.*produc/i);assert.equal(createControlledFiscalAdapter({mode:'unconfigured',production:true}).mode,'unconfigured');assert.equal(createControlledFiscalAdapter({mode:'mock-success',production:false}).mode,'mock-success');});
test('P24 sidecar requires bearer authentication before touching adapter',async()=>{let statusCalls=0;const sidecar=createFiscalSidecar({adapter:adapter({status:async()=>{statusCalls+=1;return{ok:true,status:200,data:{ready:true},error:null};}}),authToken:TOKEN,port:0});const address=await sidecar.start();const baseUrl=`http://127.0.0.1:${address.port}`;try{let response=await fetch(`${baseUrl}/v1/health`);assert.equal(response.status,401);assert.equal(statusCalls,0);response=await fetch(`${baseUrl}/v1/health`,{headers:bearer(WRONG_TOKEN)});assert.equal(response.status,401);assert.equal(statusCalls,0);response=await fetch(`${baseUrl}/v1/health`,{headers:bearer()});assert.equal(response.status,200);const body=await response.json();assert.equal(body.healthy,true);assert.equal(body.authenticated,true);assert.equal(statusCalls,1);}finally{await sidecar.stop();}});
test('P24 sidecar rejects oversized JSON before fiscal adapter issue',async()=>{let issueCalls=0;const sidecar=createFiscalSidecar({adapter:adapter({issue:async input=>{issueCalls+=1;return{ok:true,status:200,data:input,error:null};}}),authToken:TOKEN,maxBodyBytes:16*1024,port:0});const address=await sidecar.start();try{const response=await fetch(`http://127.0.0.1:${address.port}/v1/documents/nfce/VENDA-P24`,{method:'POST',headers:{...bearer(),'content-type':'application/json'},body:JSON.stringify({payload:{data:'x'.repeat(20*1024)}})});assert.equal(response.status,413);assert.equal(issueCalls,0);}finally{await sidecar.stop();}});
test('P24 sidecar sanitizes adapter error/data before crossing local HTTP boundary',async()=>{const sidecar=createFiscalSidecar({adapter:adapter({status:async()=>({ok:false,status:503,data:{password:'hunter2',nested:{token:TOKEN}},error:`Authorization: Bearer ${TOKEN}`})}),authToken:TOKEN,port:0});const address=await sidecar.start();try{const response=await fetch(`http://127.0.0.1:${address.port}/v1/health`,{headers:bearer()});const raw=await response.text();assert.equal(response.status,200);assert.doesNotMatch(raw,/hunter2/);assert.doesNotMatch(raw,new RegExp(TOKEN));assert.match(raw,/REDACTED/);}finally{await sidecar.stop();}});
test('P24 provider injects bearer token without exposing it in public status',async()=>{const calls=[];const provider=createAcbrLocalProvider({connection:{provider:'acbr-local',environment:'homologation',documentType:'nfce'},baseUrl:'http://127.0.0.1:4175',authToken:TOKEN,fetchImpl:async(url,options)=>{calls.push({url,options});return{ok:true,status:200,text:async()=>JSON.stringify({healthy:true,authenticated:true})};}});const result=await provider.testConnection();assert.equal(result.reachable,true);assert.equal(calls.length,1);assert.equal(calls[0].options.headers.authorization,`Bearer ${TOKEN}`);const publicStatus=await provider.status();assert.equal(Object.hasOwn(publicStatus,'authToken'),false);assert.equal(JSON.stringify(publicStatus).includes(TOKEN),false);});
test('P24 sidecar child environment is allowlisted and production is detected for packaged Electron',()=>{const env=buildSidecarEnv({PATH:'/bin',ARTISYS_FISCAL_SIDECAR_MODE:'acbr-monitor',ARTISYS_ACBR_HOST:'127.0.0.1',PDV_TERMINAL_KEY:'must-not-leak',FOCUS_TOKEN:'must-not-leak-either',RANDOM_SECRET:'nope'},{ARTISYS_FISCAL_SIDECAR_TOKEN:TOKEN});assert.equal(env.PATH,'/bin');assert.equal(env.ARTISYS_FISCAL_SIDECAR_MODE,'acbr-monitor');assert.equal(env.ARTISYS_FISCAL_SIDECAR_TOKEN,TOKEN);assert.equal(env.PDV_TERMINAL_KEY,undefined);assert.equal(env.FOCUS_TOKEN,undefined);assert.equal(env.RANDOM_SECRET,undefined);assert.equal(detectProductionRuntime({}, {resourcesPath:'/app/resources',defaultApp:undefined}),true);assert.equal(detectProductionRuntime({}, {resourcesPath:'/dev/resources',defaultApp:true}),false);assert.equal(detectProductionRuntime({NODE_ENV:'production'},{}),true);});