'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {createPdvRuntime}=require('../js/core/pdv-runtime');
const {storeDateKey}=require('../js/domains/shared/store-date');
const actor={userId:'admin',profileId:'profile-administrator',terminalId:'PDV-01'};
function fixture(){let timestamp='2026-10-04T01:30:00Z';const runtime=createPdvRuntime({dbPath:':memory:',now:()=>timestamp});runtime.catalog.createUser({id:'admin',username:'admin',name:'Admin',profileId:'profile-administrator',password:'senha-forte-123'},actor);runtime.modules.setEnabled('FOOD',true,actor);runtime.catalog.upsertProduct({id:'juice',name:'Suco',salePriceCents:900,trackStock:false,menuEnabled:true},actor);runtime.kitchen.configureProductRoute('juice',{mode:'DIRECT'},actor);return{runtime,setTime:value=>{timestamp=value;},close:()=>runtime.close()};}
test('store day follows Brazil midnight rather than UTC, including configured timezone',()=>{assert.equal(storeDateKey('2026-10-04T01:30:00Z'),'2026-10-03');assert.equal(storeDateKey('2026-10-04T01:30:00Z','Asia/Tokyo'),'2026-10-04');});
test('counter, pickup and delivery use the same sale and production service, optional ticket shared daily sequence',()=>{const ctx=fixture();try{const r=ctx.runtime;const old=r.fastFood.create({},actor);assert.equal(old.orderDate,'2026-10-03');const counter=r.delivery.create({channel:'COUNTER',useTicket:true,items:[{productId:'juice',quantity:1}]},actor);assert.equal(counter.channel,'COUNTER');assert.equal(counter.fulfillmentType,'PICKUP');assert.equal(counter.ticketNumber,2);assert.equal(counter.ticketDate,'2026-10-03');const sale=r.delivery.createSale(counter.id,{terminalId:'PDV-01',operatorId:'admin'},actor);assert.equal(r.delivery.get(counter.id).saleId,sale.id);assert.equal(r.delivery.get(counter.id).status,'READY');r.delivery.updateStatus(counter.id,'PICKED_UP',actor);const pickup=r.delivery.create({customerName:'Ana',fulfillmentType:'PICKUP',useTicket:true},actor);assert.equal(pickup.ticketNumber,3);assert.equal(r.fastFood.create({},actor).dailyNumber,4);const without=r.delivery.create({channel:'COUNTER'},actor);assert.equal(without.ticketNumber,null);ctx.setTime('2026-10-04T03:01:00Z');assert.equal(r.delivery.create({channel:'COUNTER',useTicket:true},actor).ticketNumber,1);assert.equal(r.fastFood.get(old.id).dailyNumber,1);}finally{ctx.close();}});
test('migration is repeatable and preserves old operational records',()=>{const ctx=fixture();try{const r=ctx.runtime;const old=r.delivery.create({customerName:'Anterior',fulfillmentType:'PICKUP'},actor);const {runFoodOrderMigrations}=require('../js/core/database/food-order-migrations');runFoodOrderMigrations(r.db);runFoodOrderMigrations(r.db);assert.equal(r.delivery.get(old.id).customerName,'Anterior');}finally{ctx.close();}});

test('shared KDS labels the actual counter, pickup and delivery channels and optional ticket',()=>{const ctx=fixture();try{const r=ctx.runtime;r.kitchen.upsertStation({id:'kitchen',name:'Cozinha',printEnabled:false},actor);r.kitchen.configureProductRoute('juice',{mode:'PRODUCTION',stationId:'kitchen'},actor);for(const channel of ['COUNTER','PICKUP','DELIVERY']){const order=r.delivery.create({channel,customerName:'Teste',useTicket:channel==='COUNTER',address:channel==='DELIVERY'?{street:'Rua',number:'10',district:'Centro',city:'São Paulo',state:'SP'}:null,items:[{productId:'juice',quantity:1}]},actor);r.delivery.createSale(order.id,{terminalId:'PDV-01',operatorId:'admin'},actor);const ticket=r.kitchen.listTickets().find(item=>item.sourceId===order.id);assert.equal(ticket.tableLabel,{COUNTER:'Balcão · Senha 1',PICKUP:'Retirada',DELIVERY:'Entrega'}[channel]);}}finally{ctx.close();}});
