'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const readJson=relative=>JSON.parse(fs.readFileSync(path.join(root,relative),'utf8'));

test('legacy UI E2E flows stay removed while current canonical audit flows remain',()=>{const flows=path.join(root,'qa','flows');const jsonFiles=fs.existsSync(flows)?fs.readdirSync(flows,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?[]:[entry.name]).filter(file=>file.endsWith('.json')).sort():[];assert.deepEqual(jsonFiles,['access-center-ergonomic.json','access-center-partial-permissions.json','all-pages-audit.json','delivery-pickup-operational-e2e.json','public-menu-compact-v2.json','semantic-regression-e2e.json']);assert.equal(fs.existsSync(path.join(root,'release','e2e-coverage.json')),false);});

test('release requires complete product-surface evidence and operation QA evidence',()=>{const pkg=readJson('package.json');assert.equal(pkg.scripts['capability:check:release'],'node scripts/check-customer-capability-parity.js --require-100');assert.match(pkg.scripts['verify:release'],/capability:check:release/);const registry=readJson('release/customer-capabilities.json');const surface=registry.capabilities.filter(item=>item.status==='supported'&&['customer','admin'].includes(item.exposure));assert.ok(surface.length>0);for(const capability of surface){for(const layer of ['backend','api','client','ui']){assert.ok(Array.isArray(capability[layer])&&capability[layer].length>0,`${capability.id} missing ${layer}`);for(const reference of capability[layer])assert.ok(fs.existsSync(path.join(root,reference.path)),`${capability.id} missing path ${reference.path}`);}assert.equal(Object.hasOwn(capability,'e2e'),false,`${capability.id} retains legacy capability-level E2E evidence`);}const operations=readJson('release/customer-operations.json').operations.filter(item=>['customer','admin'].includes(item.exposure));assert.ok(operations.length>0);for(const operation of operations){assert.ok(Array.isArray(operation.permissions)&&operation.permissions.length>0,`${operation.id} missing permissions`);assert.ok(Array.isArray(operation.qa)&&operation.qa.length>0,`${operation.id} missing qa evidence`);for(const evidence of operation.qa)assert.ok(fs.existsSync(path.join(root,evidence.path)),`${operation.id} missing qa path ${evidence.path}`);}});
