'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const {createPdvRuntime}=require('../js/core/pdv-runtime');
const {createPublicOrderingService}=require('../js/domains/restaurant/public-ordering');

const admin={userId:'admin',role:'admin',terminalId:'PDV-01'};
function fixture(){let seq=0;const rt=createPdvRuntime({dbPath:':memory:',idFactory:p=>`${p}-${++seq}`,now:()=>`2026-10-01T18:00:${String(seq%60).padStart(2,'0')}.000Z`});rt.modules.setEnabled('FOOD',true,admin);rt.catalog.upsertCategory({id:'lanches',name:'Lanches'},admin);rt.catalog.upsertProduct({id:'burger',name:'X Tudo',categoryId:'lanches',salePriceCents:2500,costCents:930,trackStock:false,menuEnabled:true,sku:'XT-01',barcode:'7890000000001'},admin);rt.catalogCustomization.upsertVariant({id:'double',productId:'burger',name:'Duplo',sku:'XT-DUPLO',barcode:'7890000000002',attributes:{tamanho:'Duplo'},priceDeltaCents:700,costCents:1300},admin);rt.catalogCustomization.upsertOptionGroup({id:'molhos',name:'Molhos',selectionType:'MULTIPLE',minSelections:0,maxSelections:2},admin);rt.catalogCustomization.upsertOption({id:'maionese',groupId:'molhos',name:'Maionese da casa',priceDeltaCents:200},admin);rt.catalogCustomization.linkGroupToProduct('burger','molhos',{required:false,sortOrder:1},admin);rt.restaurant.upsertTable({id:'mesa-1',label:'Mesa 1',seats:4},admin);rt.restaurant.upsertTable({id:'mesa-2',label:'Mesa 2',seats:4},admin);let tokenSeq=0;const service=createPublicOrderingService({db:rt.db,modules:rt.modules,catalog:rt.catalog,catalogCustomization:rt.catalogCustomization,restaurant:rt.restaurant,productPhotos:rt.productPhotos,tokenFactory:()=>`public-token-${String(++tokenSeq).padStart(8,'0')}`.padEnd(24,'x')});return{rt,service,close(){rt.close();}};}

test('public menu exposes only customer-safe product data and public description',()=>{const f=fixture();try{f.service.updateMenuProduct('burger',{description:'Pao, carne, queijo, bacon, ovo, alface e tomate.',visible:true},admin);const access=f.service.issueTableAccess('mesa-1',admin);const context=f.service.publicContext(access.token);const item=context.products.find(product=>product.id==='burger');assert.ok(item);assert.equal(item.description,'Pao, carne, queijo, bacon, ovo, alface e tomate.');assert.equal(item.salePriceCents,2500);assert.equal('costCents'in item,false);assert.equal('sku'in item,false);assert.equal('barcode'in item,false);assert.deepEqual(item.configuration.variants[0].attributes,{tamanho:'Duplo'});assert.equal('costCents'in item.configuration.variants[0],false);assert.equal('sku'in item.configuration.variants[0],false);assert.equal('barcode'in item.configuration.variants[0],false);}finally{f.close();}});

test('first QR order opens table when configured and server recalculates configured price',()=>{const f=fixture();try{const access=f.service.issueTableAccess('mesa-1',admin);const order=f.service.submitOrder(access.token,{items:[{productId:'burger',quantity:2,variantId:'double',selections:['maionese']}]},'mut-public-1');assert.equal(order.totalCents,6800);const session=f.rt.restaurant.currentSession('mesa-1');assert.ok(session);assert.equal(session.totalCents,6800);assert.equal(session.orders.length,1);assert.equal(session.orders[0].items[0].unitPriceCents,3400);assert.equal(session.orders[0].items[0].configuration.variant.id,'double');assert.equal(session.orders[0].items[0].configuration.options[0].id,'maionese');}finally{f.close();}});

test('client cannot force hidden or unavailable menu product through the public service',()=>{const f=fixture();try{const access=f.service.issueTableAccess('mesa-1',admin);f.service.updateMenuProduct('burger',{visible:false},admin);assert.equal(f.service.publicContext(access.token).products.some(product=>product.id==='burger'),false);assert.throws(()=>f.service.submitOrder(access.token,{items:[{productId:'burger',quantity:1}]},'mut-hidden'),/indisponivel|nao encontrado/i);}finally{f.close();}});

test('auto-open can be disabled while waiter call can establish an empty service session',()=>{const f=fixture();try{f.service.updateConfig({autoOpenTable:false},admin);const access=f.service.issueTableAccess('mesa-2',admin);assert.throws(()=>f.service.submitOrder(access.token,{items:[{productId:'burger',quantity:1}]},'mut-blocked'),/sem comanda/i);const call=f.service.requestService(access.token,'WAITER','mut-call');assert.equal(call.requestType,'WAITER');assert.ok(f.rt.restaurant.currentSession('mesa-2'));}finally{f.close();}});

test('rotating table access invalidates the previous QR token',()=>{const f=fixture();try{const first=f.service.issueTableAccess('mesa-1',admin);const second=f.service.rotateTableAccess('mesa-1',admin);assert.notEqual(second.token,first.token);assert.throws(()=>f.service.publicContext(first.token),/nao esta ativo/i);assert.equal(f.service.publicContext(second.token).table.label,'Mesa 1');}finally{f.close();}});


test('stock ingredients stay out of the public menu until explicitly added to Cardapio',()=>{const f=fixture();try{
  f.rt.catalog.upsertProduct({id:'bread',name:'Pao de hamburguer',salePriceCents:200,costCents:100,trackStock:true,menuEnabled:false},admin);
  const access=f.service.issueTableAccess('mesa-1',admin);
  assert.equal(f.service.publicContext(access.token).products.some(product=>product.id==='bread'),false);
  assert.throws(()=>f.service.submitOrder(access.token,{items:[{productId:'bread',quantity:1}]},'mut-ingredient'),/indisponivel|nao encontrado/i);
}finally{f.close();}});
