'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const { createPdvRuntime }=require('../js/core/pdv-runtime');
const actor={userId:'u1',role:'manager',terminalId:'T1'};
function setup(){let seq=0;const r=createPdvRuntime({now:()=> '2026-09-20T14:00:00.000Z',idFactory:p=>`${p}-${++seq}`});r.catalog.createUser({id:'u1',username:'gerente',name:'Gerente',role:'manager',password:'senha-forte'},actor);r.catalog.upsertCustomer({id:'c1',name:'Cliente'},actor);r.catalog.upsertProduct({id:'p1',name:'Produto',salePriceCents:1000,costCents:500,trackStock:true},actor);r.inventory.move({productId:'p1',type:'opening',quantityDelta:10},actor);return r;}

test('quote confirmation reserves stock and cancellation releases it',()=>{const r=setup();assert.ok(r.orders);const order=r.orders.createQuote({customerId:'c1',locationId:'MAIN',fulfillmentType:'PICKUP',items:[{productId:'p1',quantity:6}]},actor);assert.equal(order.status,'QUOTED');r.orders.confirmOrder(order.id,actor);assert.equal(r.orders.getOrder(order.id).status,'CONFIRMED');assert.equal(r.logistics.getAvailability('p1','MAIN').availableQuantity,4);r.orders.cancelOrder(order.id,{reason:'Cliente desistiu'},actor);assert.equal(r.logistics.getAvailability('p1','MAIN').availableQuantity,10);assert.equal(r.orders.getOrder(order.id).status,'CANCELLED');r.close();});

test('partial and final fulfillment reuse canonical sale and are idempotent',async()=>{const r=setup();const order=r.orders.createQuote({customerId:'c1',locationId:'MAIN',fulfillmentType:'PICKUP',items:[{productId:'p1',quantity:6}]},actor);r.orders.confirmOrder(order.id,actor);const first=r.orders.fulfillOrder(order.id,{idempotencyKey:'fulfill-1',items:[{productId:'p1',quantity:2}],payments:[{method:'CASH',amountCents:2000}],terminalId:'T1',operatorId:'u1',sellerId:'u1'},actor);assert.equal(first.status,'COMPLETED');assert.ok(first.saleId);const retry=r.orders.fulfillOrder(order.id,{idempotencyKey:'fulfill-1',items:[{productId:'p1',quantity:2}],payments:[{method:'CASH',amountCents:2000}],terminalId:'T1',operatorId:'u1',sellerId:'u1'},actor);assert.equal(retry.saleId,first.saleId);await r.dispatchPending();assert.equal(r.orders.getOrder(order.id).status,'PARTIALLY_FULFILLED');assert.equal(r.inventory.getBalance('p1',{locationId:'MAIN'}),8);assert.equal(r.logistics.getAvailability('p1','MAIN').availableQuantity,4);const second=r.orders.fulfillOrder(order.id,{idempotencyKey:'fulfill-2',items:[{productId:'p1',quantity:4}],payments:[{method:'CASH',amountCents:4000}],terminalId:'T1',operatorId:'u1',sellerId:'u1'},actor);await r.dispatchPending();assert.equal(second.status,'COMPLETED');assert.equal(r.orders.getOrder(order.id).status,'FULFILLED');assert.equal(r.inventory.getBalance('p1',{locationId:'MAIN'}),4);assert.equal(r.logistics.listReservations({sourceType:'sales-order',sourceId:order.id}).filter(x=>x.status==='ACTIVE').length,0);r.close();});

test('fulfillment rejects quantity above remaining order quantity atomically',()=>{const r=setup();const order=r.orders.createQuote({customerId:'c1',locationId:'MAIN',fulfillmentType:'DELIVERY',items:[{productId:'p1',quantity:3}]},actor);r.orders.confirmOrder(order.id,actor);assert.throws(()=>r.orders.fulfillOrder(order.id,{idempotencyKey:'fulfill-over',items:[{productId:'p1',quantity:4}],payments:[{method:'CASH',amountCents:4000}],terminalId:'T1',operatorId:'u1',sellerId:'u1'},actor),/excede.*pendente/i);assert.equal(r.sales.listSales({}).length,0);assert.equal(r.orders.getOrder(order.id).status,'CONFIRMED');r.close();});
