'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {createTelemetryIdentity}=require('../js/core/telemetry/telemetry-identity');
const {createTelemetryService}=require('../js/core/telemetry/telemetry-service');
function settings(initial={}){const m=new Map(Object.entries(initial));return{get:(k,{defaultValue}={})=>m.has(k)?m.get(k):defaultValue,set:(k,v)=>{m.set(k,v);return{key:k,value:v};},m};}
function service({enabled=false,sender=null,db=new DatabaseSync(':memory:')}={}){let i=0;const s=settings({'telemetry.enabled':enabled,'telemetry.endpoint':enabled?'https://t.invalid':'','telemetry.batchSize':50});const identity=createTelemetryIdentity({db,randomUUID:()=>`00000000-0000-4000-8000-${String(++i).padStart(12,'0')}`});const telemetry=createTelemetryService({db,settings:s,logger:{log(){}},identity,now:()=> '2026-09-25T12:00:00.000Z',idFactory:p=>`${p}-${++i}`,httpSender:sender,appVersion:'1.4.1',releaseId:'abc',schemaVersionResolver:()=>42,random:()=>0});return{db,s,telemetry};}

test('telemetry is disabled by default and records nothing',()=>{const x=service();assert.equal(x.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'}),false);assert.equal(x.telemetry.status().pending,0);x.db.close();});
test('record is fail-open when local persistence fails',()=>{const x=service({enabled:true});x.db.close();assert.doesNotThrow(()=>x.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'}));});
test('flush batches success and discards invalid 4xx',async()=>{const statuses=[200,422];const sender={sendBatch:async()=>({status:statuses.shift()})};const x=service({enabled:true,sender});for(let i=0;i<51;i++)x.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'});let r=await x.telemetry.flush();assert.equal(r.sent,50);assert.equal(x.telemetry.status().pending,1);r=await x.telemetry.flush();assert.equal(r.discarded,1);assert.equal(x.telemetry.status().pending,0);x.db.close();});
test('401 pauses and 5xx/network reschedule without throwing',async()=>{const sender={sendBatch:async()=>({status:401})};const x=service({enabled:true,sender});x.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'});let r=await x.telemetry.flush();assert.equal(r.paused,true);assert.equal(x.telemetry.status().pending,1);x.db.close();const y=service({enabled:true,sender:{sendBatch:async()=>({status:503})}});y.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'});r=await y.telemetry.flush();assert.equal(r.retryable,1);assert.equal(y.telemetry.status().pending,1);y.db.close();});
test('disabling after queue prevents send until reenabled',async()=>{let calls=0;const x=service({enabled:true,sender:{sendBatch:async()=>{calls++;return{status:200};}}});x.telemetry.record('screen_opened',{dimensions:{route:'sales'}},{terminalKey:'PDV-01'});x.s.m.set('telemetry.enabled',false);let r=await x.telemetry.flush();assert.equal(calls,0);assert.equal(r.paused,true);x.s.m.set('telemetry.enabled',true);r=await x.telemetry.flush();assert.equal(calls,1);assert.equal(r.sent,1);x.db.close();});
