'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {Readable}=require('node:stream');
const {createTelemetryRouter,validateUiTelemetryEvent}=require('../server/telemetry-router');
function request(body,token='session'){const req=Readable.from([JSON.stringify(body)]);req.method='POST';req.url='/api/v1/system/telemetry/events';req.headers={host:'localhost',authorization:token?`Bearer ${token}`:''};return req;}
function response(){return{statusCode:0,payload:null,writeHead(code){this.statusCode=code;},end(text){this.payload=text?JSON.parse(text):null;}};}
test('UI telemetry endpoint requires an authenticated session',async()=>{const runtime={telemetry:{record(){throw new Error('must not run');}}};const route=createTelemetryRouter({runtime,sessionStore:new Map()});const res=response();assert.equal(await route(request({eventName:'screen_opened',payload:{dimensions:{route:'home'}}},''),res),true);assert.equal(res.statusCode,401);});
test('UI telemetry rejects events and routes outside the allowlist',()=>{assert.throws(()=>validateUiTelemetryEvent('sale_completed',{}),/nao permitido/i);assert.throws(()=>validateUiTelemetryEvent('screen_opened',{dimensions:{route:'sales/123?cpf=x'}}),/rota/i);});
test('valid UI telemetry records only pseudonym lookup key, not terminal data in payload',async()=>{const calls=[];const runtime={telemetry:{record:(...args)=>calls.push(args)}};const sessions=new Map([['session',{userId:'u1',role:'cashier',terminalId:'PDV-REAL-99',expiresAt:Date.now()+60000}]]);const route=createTelemetryRouter({runtime,sessionStore:sessions});const res=response();await route(request({eventName:'screen_opened',payload:{dimensions:{route:'returns'}}}),res);assert.equal(res.statusCode,202);assert.equal(calls[0][0],'screen_opened');assert.deepEqual(calls[0][1],{dimensions:{route:'returns'},measurements:{}});assert.equal(calls[0][2].terminalKey,'PDV-REAL-99');assert.equal(JSON.stringify(calls[0][1]).includes('PDV-REAL-99'),false);});
test('privacy UI cannot grant initial consent and explicitly lists data never collected',()=>{const source=fs.readFileSync(path.join(__dirname,'../desktop/renderer/telemetry-ui.js'),'utf8');for(const text of ['telemetry.enabled','telemetry.diagnostics','telemetry.consent_version','telemetry.consent_accepted_at','não nesta tela','CPF/CNPJ','senha','token','XML/DANFE','dados de cartão','texto digitado'])assert.equal(source.includes(text),true,text);assert.equal(source.includes('credentialStore'),false);assert.equal(source.includes('PDV_TELEMETRY_ENDPOINT'),false);});
