'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {validateTelemetryEvent}=require('../js/core/telemetry/telemetry-events');
const {sanitizeTelemetryEnvelope}=require('../js/core/telemetry/telemetry-sanitizer');
const {fingerprintError,normalizeErrorSignature}=require('../js/core/telemetry/telemetry-fingerprint');

test('unknown telemetry event and fields are rejected',()=>{assert.throws(()=>validateTelemetryEvent('mystery',{}),/evento/i);assert.throws(()=>validateTelemetryEvent('screen_opened',{dimensions:{route:'sales',customerName:'Ana'}}),/campo/i);});
test('sensitive field names are rejected before persistence',()=>{for(const key of ['token','authorization','password','cpf','cnpj','email','phone','address','xml','danfe','card','cvv','observation'])assert.throws(()=>sanitizeTelemetryEnvelope({schema_version:1,event_id:'e1',event_name:'operation_failed',occurred_at:'2026-09-25T00:00:00Z',installation_id:'i',terminal_id:'t',session_id:'s',app_version:'1',release_id:'r',database_schema_version:1,dimensions:{module:'core',[key]:'secret'},measurements:{}}),/proibido|sensivel/i,key);});
test('strings are bounded and safe envelopes keep only known top-level fields',()=>{assert.throws(()=>validateTelemetryEvent('screen_opened',{dimensions:{route:'x'.repeat(129)}}),/limite/i);const out=sanitizeTelemetryEnvelope({schema_version:1,event_id:'e1',event_name:'screen_opened',occurred_at:'2026-09-25T00:00:00Z',installation_id:'i',terminal_id:'t',session_id:'s',app_version:'1',release_id:'r',database_schema_version:1,dimensions:{route:'sales'},measurements:{},extra:'drop'});assert.equal('extra' in out,false);assert.equal(out.dimensions.route,'sales');});
test('fingerprint ignores dynamic ids and user paths but changes by technical class',()=>{const a=fingerprintError({errorClass:'TypeError',subsystem:'fiscal',operation:'authorize',stack:'TypeError: fail at C:\\Users\\alice\\app\\x.js:123:44 request 550e8400-e29b-41d4-a716-446655440000 id 938423'});const b=fingerprintError({errorClass:'TypeError',subsystem:'fiscal',operation:'authorize',stack:'TypeError: fail at C:\\Users\\bob\\app\\x.js:999:2 request 123e4567-e89b-12d3-a456-426614174000 id 123'});const c=fingerprintError({errorClass:'RangeError',subsystem:'fiscal',operation:'authorize',stack:'TypeError: fail at C:\\Users\\bob\\app\\x.js:999:2 request 123e4567-e89b-12d3-a456-426614174000 id 123'});assert.equal(a,b);assert.notEqual(a,c);assert.match(a,/^ERR-[0-9a-f]{16}$/);assert.equal(normalizeErrorSignature({errorClass:'TypeError',subsystem:'fiscal',operation:'authorize',stack:'x'}).includes('alice'),false);});
