'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {EventEmitter}=require('node:events');
const {registerTelemetryEffects}=require('../js/core/telemetry/telemetry-effects');
const {classifyTelemetryHttpFailure,observeTelemetryResponse}=require('../js/core/telemetry/telemetry-http');
function bus(){const handlers=new Map();return{subscribe:(name,fn)=>{handlers.set(name,fn);return()=>handlers.delete(name);},emit:(name,event)=>handlers.get(name)?.(event)};}
test('domain telemetry maps semantic events without copying actor or business payload',()=>{const b=bus();const records=[];registerTelemetryEffects({bus:b,telemetry:{record:(name,payload)=>records.push({name,payload})}});b.emit('sale.completed',{actor:{userId:'secret-user'},payload:{customerId:'c1',productName:'Private',observation:'do not send'}});assert.deepEqual(records,[{name:'sale_completed',payload:{dimensions:{module:'pos',result:'success'}}}]);assert.equal(JSON.stringify(records).includes('secret-user'),false);assert.equal(JSON.stringify(records).includes('Private'),false);});
test('domain failure events receive technical fingerprints without raw payload',()=>{const b=bus();const records=[];registerTelemetryEffects({bus:b,telemetry:{record:(name,payload)=>records.push({name,payload})}});b.emit('fiscal.failed',{payload:{xml:'secret',message:'provider raw error'}});const row=records.at(-1);assert.equal(row.name,'fiscal_failed');assert.match(row.payload.dimensions.fingerprint,/^ERR-[0-9a-f]{16}$/);assert.equal(row.payload.dimensions.error_class,'domain_failure');assert.equal(JSON.stringify(row).includes('secret'),false);assert.equal(JSON.stringify(row).includes('provider raw error'),false);});
test('telemetry effect is fail-open even when record throws',()=>{const b=bus();registerTelemetryEffects({bus:b,telemetry:{record:()=>{throw new Error('telemetry down');}}});assert.doesNotThrow(()=>b.emit('sale.completed',{payload:{}}));});
test('http classifier only maps technical 5xx and strips query ids',()=>{const sale=classifyTelemetryHttpFailure({method:'POST',pathname:'/api/v1/sales/abc/complete?customer=123',status:500});assert.equal(sale.eventName,'sale_failed');assert.deepEqual({...sale.dimensions,fingerprint:undefined},{module:'pos',operation:'sale_mutation',error_class:'http_5xx',fingerprint:undefined});assert.match(sale.dimensions.fingerprint,/^ERR-[0-9a-f]{16}$/);assert.equal(classifyTelemetryHttpFailure({method:'POST',pathname:'/api/v1/sales/a/complete',status:400}),null);assert.equal(classifyTelemetryHttpFailure({method:'GET',pathname:'/unknown',status:500}),null);assert.equal(JSON.stringify(classifyTelemetryHttpFailure({method:'POST',pathname:'/api/v1/returns/r1?cpf=123',status:503})).includes('r1'),false);});
test('response observer records real terminal only as local lookup key',()=>{const response=new EventEmitter();response.statusCode=500;const records=[];const req={method:'POST',url:'/api/v1/returns/r1',headers:{'x-terminal-id':'PDV-REAL-99'}};observeTelemetryResponse({request:req,response,telemetry:{record:(...args)=>records.push(args)}});response.emit('finish');assert.equal(records[0][0],'return_failed');assert.equal(records[0][2].terminalKey,'PDV-REAL-99');assert.equal(JSON.stringify(records[0][1]).includes('PDV-REAL-99'),false);assert.match(records[0][1].dimensions.fingerprint,/^ERR-[0-9a-f]{16}$/);});
test('registerTelemetryEffects is idempotent for loopback and LAN on same bus',()=>{const b=bus();let count=0;const telemetry={record:()=>count++};registerTelemetryEffects({bus:b,telemetry});registerTelemetryEffects({bus:b,telemetry});b.emit('sale.opened',{});assert.equal(count,1);});
