'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const { createPdvRuntime }=require('../../js/core/pdv-runtime');

const root=path.resolve(__dirname,'../..');
const actor={userId:'manager',role:'manager',terminalId:'PDV-01'};
function setup(){let seq=0;const runtime=createPdvRuntime({now:()=> '2026-09-20T15:00:00.000Z',idFactory:p=>`${p}-${++seq}`});runtime.catalog.createUser({id:'manager',username:'manager',name:'Gerente',role:'manager',password:'senha-forte-123'},actor);runtime.catalog.upsertSupplier({id:'supplier',name:'Fornecedor'},actor);runtime.catalog.upsertCustomer({id:'customer',name:'Cliente'},actor);runtime.catalog.upsertProduct({id:'product',name:'Produto',salePriceCents:1200,costCents:600,trackStock:true},actor);runtime.inventory.move({productId:'product',type:'opening',quantityDelta:10},actor);return runtime;}

test('phase 9 operational chain joins purchase location transfer reservation order and canonical sale',async()=>{const runtime=setup();runtime.logistics.createLocation({id:'DEP',name:'Deposito',type:'WAREHOUSE'},actor);const po=runtime.procurement.createPurchaseOrder({supplierId:'supplier',locationId:'DEP',items:[{productId:'product',quantity:10,unitCostCents:800}]},actor);runtime.procurement.submitPurchaseOrder(po.id,actor);runtime.procurement.receivePurchaseOrder(po.id,{idempotencyKey:'receipt-phase9',items:[{productId:'product',quantity:10}]},actor);assert.equal(runtime.inventory.getBalance('product',{locationId:'DEP'}),10);const transfer=runtime.logistics.createTransfer({fromLocationId:'DEP',toLocationId:'MAIN',items:[{productId:'product',quantity:4}]},actor);runtime.logistics.dispatchTransfer(transfer.id,{idempotencyKey:'dispatch-phase9'},actor);assert.equal(runtime.inventory.getBalance('product',{locationId:'DEP'}),6);assert.equal(runtime.inventory.getBalance('product',{locationId:'MAIN'}),10);runtime.logistics.receiveTransfer(transfer.id,{idempotencyKey:'receive-phase9'},actor);assert.equal(runtime.inventory.getBalance('product',{locationId:'MAIN'}),14);const order=runtime.orders.createQuote({customerId:'customer',locationId:'MAIN',fulfillmentType:'PICKUP',items:[{productId:'product',quantity:3}]},actor);runtime.orders.confirmOrder(order.id,actor);assert.equal(runtime.logistics.getAvailability('product','MAIN').availableQuantity,11);const fulfillment=runtime.orders.fulfillOrder(order.id,{idempotencyKey:'fulfill-phase9',items:[{productId:'product',quantity:3}],payments:[{method:'CASH',amountCents:3600}],terminalId:'PDV-01',operatorId:'manager',sellerId:'manager'},actor);assert.ok(fulfillment.saleId);await runtime.dispatchPending();assert.equal(runtime.inventory.getBalance('product',{locationId:'MAIN'}),11);assert.equal(runtime.orders.getOrder(order.id).status,'FULFILLED');const sold=runtime.db.prepare('SELECT cost_cents_snapshot,cost_snapshot_source FROM sale_items WHERE sale_id=?').get(fulfillment.saleId);assert.equal(sold.cost_cents_snapshot,700);assert.equal(sold.cost_snapshot_source,'PRODUCT');runtime.close();});

test('phase 9 customer surface is wired from API through desktop UI',()=>{const server=fs.readFileSync(path.join(root,'server/enterprise-depth-router.js'),'utf8');const client=fs.readFileSync(path.join(root,'desktop/renderer/enterprise-depth-api-client.js'),'utf8');const ui=fs.readFileSync(path.join(root,'desktop/renderer/enterprise-depth-ui.js'),'utf8');const index=fs.readFileSync(path.join(root,'desktop/renderer/index.html'),'utf8');for(const route of ['/api/v1/stock-locations','/api/v1/stock-transfers','/api/v1/purchase-orders','/api/v1/sales-orders'])assert.match(server,new RegExp(route.replace(/\//g,'\\/')));for(const method of ['createStockTransfer','createPurchaseOrder','createSalesQuote','fulfillSalesOrder'])assert.match(client,new RegExp(method));for(const label of ['Compras e recebimentos','Logística de estoque','Orçamentos e pedidos'])assert.match(ui,new RegExp(label));assert.match(index,/enterprise-depth-api-client\.js/);assert.match(index,/enterprise-depth-ui\.js/);});
