'use strict';
function createFinanceAlertService({db,finance,financeManagement,settings,now=()=>new Date().toISOString()}={}){
  if(!db||!finance||!financeManagement||!settings)throw new TypeError('finance alert dependencies are required.');
  const today=()=>String(now()).slice(0,10);const plusDays=(text,n)=>{const d=new Date(`${text}T00:00:00.000Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);};
  function state(key){return db.prepare('SELECT * FROM finance_alert_state WHERE alert_key=?').get(key)||null;}
  function accountBalance(accountId){const row=db.prepare(`SELECT COALESCE(SUM(CASE WHEN fe.kind='RECEIVABLE' THEN fs.amount_cents ELSE -fs.amount_cents END),0) balance FROM financial_settlements fs JOIN financial_entries fe ON fe.id=fs.entry_id WHERE fs.reversed_at IS NULL AND fe.status<>'CANCELLED' AND fe.account_id=?`).get(String(accountId));return Number(row?.balance||0);}
  function decorate(alert){const s=state(alert.key);return{...alert,readAt:s?.read_at||null,hiddenAt:s?.hidden_at||null};}
  function list({includeHidden=false}={}){const date=today(),soon=plusDays(date,7);const alerts=[];for(const entry of finance.listEntries({asOf:`${date}T23:59:59.999Z`}).filter(row=>row.kind==='PAYABLE'&&row.openCents>0&&row.status!=='CANCELLED')){const due=String(entry.dueAt||'').slice(0,10);if(due<date)alerts.push({key:`OVERDUE_PAYABLE:${entry.id}`,kind:'OVERDUE_PAYABLE',severity:'high',entryId:entry.id,amountCents:entry.openCents,dueDate:due,message:`Conta vencida: ${entry.description}`});else if(due<=soon)alerts.push({key:`DUE_SOON_PAYABLE:${entry.id}`,kind:'DUE_SOON_PAYABLE',severity:'medium',entryId:entry.id,amountCents:entry.openCents,dueDate:due,message:`Conta vence em breve: ${entry.description}`});}
    for(const account of finance.listAccounts()){const threshold=Number(settings.get(`finance.alerts.lowBalanceCents.${account.id}`,{defaultValue:NaN}));if(Number.isFinite(threshold)){const balance=accountBalance(account.id);if(balance<threshold)alerts.push({key:`LOW_ACCOUNT_BALANCE:${account.id}`,kind:'LOW_ACCOUNT_BALANCE',severity:'medium',accountId:account.id,balanceCents:balance,thresholdCents:threshold,message:`Saldo operacional abaixo do limite em ${account.name}`});}}
    for(const days of [7,30,90]){const flow=financeManagement.cashflow({from:date,to:date,projectionDays:days});if(flow.projectedClosingDeltaCents<0)alerts.push({key:`NEGATIVE_CASH_PROJECTION:${days}:${date}`,kind:'NEGATIVE_CASH_PROJECTION',severity:days<=7?'high':'medium',projectionDays:days,amountCents:flow.projectedClosingDeltaCents,message:`Projecao de caixa negativa em ${days} dias`});}
    return alerts.map(decorate).filter(row=>includeHidden||!row.hiddenAt);}
  function setState(key,patch={}){const ts=now(),old=state(key)||{};db.prepare(`INSERT INTO finance_alert_state(alert_key,read_at,hidden_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(alert_key) DO UPDATE SET read_at=excluded.read_at,hidden_at=excluded.hidden_at,updated_at=excluded.updated_at`).run(String(key),patch.readAt!==undefined?patch.readAt:old.read_at||null,patch.hiddenAt!==undefined?patch.hiddenAt:old.hidden_at||null,ts);return state(key);}
  const markRead=key=>setState(key,{readAt:now()});const hide=key=>setState(key,{hiddenAt:now()});const unhide=key=>setState(key,{hiddenAt:null});
  return{list,markRead,hide,unhide};
}
module.exports={createFinanceAlertService};
