'use strict';
const {randomUUID}=require('node:crypto');
const {withTransaction}=require('../../core/database/sqlite-database');
const {writeAudit}=require('../../core/audit-log');
const {normalizeBusinessDate}=require('./finance-dimensions');
function daysInMonth(year,month){return new Date(Date.UTC(year,month,0)).getUTCDate();}
function dueFor(year,month,dueDay){const day=Math.min(dueDay,daysInMonth(year,month));return `${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}
function nextMonthDue(dateText,dueDay,intervalMonths=1){const d=new Date(`${dateText}T00:00:00.000Z`);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+intervalMonths);return dueFor(d.getUTCFullYear(),d.getUTCMonth()+1,dueDay);}
function firstDue(startDate,dueDay){const d=new Date(`${startDate}T00:00:00.000Z`);const current=dueFor(d.getUTCFullYear(),d.getUTCMonth()+1,dueDay);return current>=startDate?current:nextMonthDue(current,dueDay,1);}
function createRecurrenceService({db,finance,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
  if(!db||!finance)throw new TypeError('db and finance are required.');
  const manager=actor=>{if(!['admin','manager','system'].includes(String(actor?.role||'')))throw new Error('Permissao insuficiente.');};
  const map=row=>row&&({id:row.id,kind:row.kind,description:row.description,categoryId:row.category_id,costCenterId:row.cost_center_id,accountId:row.account_id,amountCents:Number(row.amount_cents),startDate:row.start_date,endDate:row.end_date,dueDay:Number(row.due_day),intervalMonths:Number(row.interval_months),maxOccurrences:row.max_occurrences==null?null:Number(row.max_occurrences),generatedCount:Number(row.generated_count),nextDueAt:row.next_due_at,status:row.status,notes:row.notes,createdAt:row.created_at,updatedAt:row.updated_at});
  function createRule(input={},actor={}){manager(actor);const kind=String(input.kind||'').toUpperCase();if(!['PAYABLE','RECEIVABLE'].includes(kind))throw new Error('Tipo de recorrencia invalido.');const description=String(input.description||'').trim();if(!description)throw new Error('Descricao obrigatoria.');const amountCents=Number(input.amountCents);if(!Number.isInteger(amountCents)||amountCents<=0)throw new Error('Valor invalido.');const startDate=normalizeBusinessDate(input.startDate,{required:true});const endDate=input.endDate?normalizeBusinessDate(input.endDate,{required:true}):null;if(endDate&&endDate<startDate)throw new Error('Data final anterior a inicial.');const dueDay=Number(input.dueDay);if(!Number.isInteger(dueDay)||dueDay<1||dueDay>31)throw new Error('Dia de vencimento invalido.');const intervalMonths=Number(input.intervalMonths||1);if(!Number.isInteger(intervalMonths)||intervalMonths<1||intervalMonths>12)throw new Error('Intervalo mensal invalido.');const maxOccurrences=input.maxOccurrences==null?null:Number(input.maxOccurrences);if(maxOccurrences!==null&&(!Number.isInteger(maxOccurrences)||maxOccurrences<1))throw new Error('Maximo de ocorrencias invalido.');const id=String(input.id||idFactory('rec'));const ts=now();const nextDueAt=firstDue(startDate,dueDay);db.prepare(`INSERT INTO finance_recurring_rules(id,kind,description,category_id,cost_center_id,account_id,amount_cents,start_date,end_date,due_day,interval_months,max_occurrences,generated_count,next_due_at,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0,?,'ACTIVE',?,?,?)`).run(id,kind,description,input.categoryId||null,input.costCenterId||null,input.accountId||null,amountCents,startDate,endDate,dueDay,intervalMonths,maxOccurrences,nextDueAt,input.notes||null,ts,ts);writeAudit(db,{action:'finance.recurrence.create',entity:'finance-recurrence',entityId:id,actor,context:{kind,amountCents,nextDueAt}},now);return map(db.prepare('SELECT * FROM finance_recurring_rules WHERE id=?').get(id));}
  function listRules({status=null}={}){const rows=status?db.prepare('SELECT * FROM finance_recurring_rules WHERE status=? ORDER BY next_due_at,id').all(String(status).toUpperCase()):db.prepare('SELECT * FROM finance_recurring_rules ORDER BY next_due_at,id').all();return rows.map(map);}
  function setRuleStatus(id,status,actor={}){manager(actor);const value=String(status||'').toUpperCase();if(!['ACTIVE','PAUSED','ENDED'].includes(value))throw new Error('Status invalido.');const result=db.prepare('UPDATE finance_recurring_rules SET status=?,updated_at=? WHERE id=?').run(value,now(),String(id));if(!result.changes)throw new Error('Recorrencia nao encontrada.');writeAudit(db,{action:'finance.recurrence.status',entity:'finance-recurrence',entityId:String(id),actor,context:{status:value}},now);return map(db.prepare('SELECT * FROM finance_recurring_rules WHERE id=?').get(String(id)));}
  function generateDue({asOf=null}={},actor={userId:'system',role:'system'}){manager(actor);const limit=normalizeBusinessDate(asOf||String(now()).slice(0,10),{required:true});const generated=[];for(const initial of db.prepare("SELECT * FROM finance_recurring_rules WHERE status='ACTIVE' AND next_due_at<=? ORDER BY next_due_at,id").all(limit)){let rule=initial;while(rule.status==='ACTIVE'&&rule.next_due_at<=limit){const due=rule.next_due_at;if(rule.end_date&&due>rule.end_date){db.prepare("UPDATE finance_recurring_rules SET status='ENDED',updated_at=? WHERE id=?").run(now(),rule.id);break;}if(rule.max_occurrences!==null&&Number(rule.generated_count)>=Number(rule.max_occurrences)){db.prepare("UPDATE finance_recurring_rules SET status='ENDED',updated_at=? WHERE id=?").run(now(),rule.id);break;}const key=due;const existing=db.prepare('SELECT entry_id FROM finance_recurrence_occurrences WHERE recurrence_id=? AND occurrence_key=?').get(rule.id,key);if(!existing){const entryId=String(idFactory('fin'));withTransaction(db,()=>{const again=db.prepare('SELECT entry_id FROM finance_recurrence_occurrences WHERE recurrence_id=? AND occurrence_key=?').get(rule.id,key);if(again)return;finance.createEntry({id:entryId,kind:rule.kind,description:rule.description,categoryId:rule.category_id||null,costCenterId:rule.cost_center_id||null,accountId:rule.account_id||null,amountCents:Number(rule.amount_cents),dueAt:`${due}T12:00:00.000Z`,competencyDate:`${due.slice(0,7)}-01`,sourceType:'finance-recurrence',sourceId:rule.id,notes:rule.notes||null},actor);db.prepare('INSERT INTO finance_recurrence_occurrences(recurrence_id,occurrence_key,entry_id,generated_at) VALUES(?,?,?,?)').run(rule.id,key,entryId,now());});generated.push({recurrenceId:rule.id,occurrenceKey:key,entryId});}
        const count=Number(rule.generated_count)+1;const next=nextMonthDue(due,Number(rule.due_day),Number(rule.interval_months));let status='ACTIVE';if((rule.max_occurrences!==null&&count>=Number(rule.max_occurrences))||(rule.end_date&&next>rule.end_date))status='ENDED';db.prepare('UPDATE finance_recurring_rules SET generated_count=?,next_due_at=?,status=?,updated_at=? WHERE id=?').run(count,next,status,now(),rule.id);rule=db.prepare('SELECT * FROM finance_recurring_rules WHERE id=?').get(rule.id);
      }}if(generated.length)writeAudit(db,{action:'finance.recurrence.generate',entity:'finance-recurrence',entityId:'batch',actor,context:{asOf:limit,count:generated.length}},now);return generated;}
  return{createRule,listRules,setRuleStatus,generateDue};
}
module.exports={createRecurrenceService,firstDue,nextMonthDue};
