'use strict';

(()=>{
  const root=document.getElementById('app');const toast=document.getElementById('toast');
  let credential={id:localStorage.getItem('artisys.deviceId')||'',key:localStorage.getItem('artisys.deviceKey')||''};
  const composer=window.PdvOrderComposer;if(!composer)throw new Error('Compositor de pedido indisponível.');
  let context=null;let selectedTableId='';const cart=composer.createCart();let refreshing=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const mutationId=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
  const labels={ACTIVE:'Ativo',FREE:'Livre',OCCUPIED:'Ocupada',BILL_REQUESTED:'Conta solicitada',CHECKOUT:'Fechamento',OPEN:'Aberto',ACKNOWLEDGED:'Em atendimento',NEW:'Novo',PREPARING:'Em preparo',READY:'Pronto',CANCELLED:'Cancelado',BLOCKED:'Bloqueado'};
  const status=value=>`<span class="status ${esc(value)}">${esc(labels[value]||value)}</span>`;
  const age=value=>{const ms=Date.now()-Date.parse(value||'');if(!Number.isFinite(ms))return'';const minutes=Math.max(0,Math.floor(ms/60000));return minutes<1?'agora':`${minutes} min`;};
  function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}
  async function request(path,{method='GET',body:payload,mutation=false}={}){const headers={'x-device-id':credential.id,'x-device-key':credential.key};if(payload!==undefined)headers['content-type']='application/json';if(mutation)headers['x-mutation-id']=mutationId();const response=await fetch(path,{method,headers,body:payload===undefined?undefined:JSON.stringify(payload)});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.error||`Erro HTTP ${response.status}`);return data;}
  function login(){root.innerHTML=`<section class="login-shell"><div class="login-copy"><span class="eyebrow">DISPOSITIVO DA EQUIPE</span><h1>Conectar ao restaurante</h1><p>Use a credencial criada no PDV para garçom, tablet, cozinha ou quiosque. Clientes usam o QR da mesa e não precisam desta tela.</p></div><form id="login" class="panel login-panel" novalidate><label class="field">ID do dispositivo<input name="id" autocomplete="username" required value="${esc(credential.id)}"></label><label class="field">Chave do dispositivo<input name="key" type="password" autocomplete="current-password" required></label><div id="login-error" class="inline-error hidden" role="alert"></div><button class="btn" type="submit">Conectar</button></form></section>`;document.getElementById('login').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);credential={id:String(form.get('id')).trim(),key:String(form.get('key'))};localStorage.setItem('artisys.deviceId',credential.id);localStorage.setItem('artisys.deviceKey',credential.key);try{await refresh();}catch(error){const node=document.getElementById('login-error');if(node){node.textContent=error.message;node.classList.remove('hidden');}}});}
  function logout(){localStorage.removeItem('artisys.deviceId');localStorage.removeItem('artisys.deviceKey');credential={id:'',key:''};context=null;cart.clear();login();}
  async function refresh({quiet=false}={}){if(refreshing)return;if(!credential.id||!credential.key){login();return;}refreshing=true;try{context=await request('/api/v1/mobile/context');render();}catch(error){if(!quiet){notify(error.message);throw error;}}finally{refreshing=false;}}
  function shell(title,subtitle,body,{toolbar=''}={}){root.innerHTML=`<section class="staff-head"><div><span class="eyebrow">${esc(context?.device?.deviceType||'EQUIPE')}</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="head-actions">${toolbar}<button id="logout" class="btn ghost" type="button">Sair</button></div></section>${body}`;document.getElementById('logout')?.addEventListener('click',logout);}
  function hasConfiguration(product){const cfg=product?.configuration||{};return Boolean(cfg.variants?.length||cfg.groups?.length||cfg.combos?.length);}
  function products(list){return `<section class="panel"><div class="section-head"><div><span class="eyebrow">CARDÁPIO</span><h2>Adicionar itens</h2></div></div><div class="product-list">${(list||[]).map(p=>`<div class="product"><div><strong>${esc(p.name)}</strong><small>${esc(p.categoryName||'Outros')} · ${money(p.salePriceCents)}</small></div><button data-add="${esc(p.id)}" type="button" aria-label="Adicionar ${esc(p.name)}">${hasConfiguration(p)?'Escolher':'Adicionar'}</button></div>`).join('')||'<div class="empty">Nenhum produto cadastrado.</div>'}</div></section>`;}
  function optionDelta(delta){const value=Number(delta||0);return value?` (${value>0?'+':''}${money(value)})`:'';}
  function configureProduct(product){
    if(!hasConfiguration(product)){cart.add({productId:product.id,name:product.name,unitPriceCents:product.salePriceCents,quantity:1});render();return;}
    const cfg=product.configuration||{};const dialog=document.createElement('dialog');dialog.className='panel product-config-dialog';
    const variants=(cfg.variants||[]).map(v=>`<label class="field"><span>${esc(v.name)}${optionDelta(v.priceDeltaCents)}</span><input type="radio" name="variantId" value="${esc(v.id)}"></label>`).join('');
    const groups=(cfg.groups||[]).map(g=>`<fieldset data-group="${esc(g.id)}" data-min="${Math.max(Number(g.minSelections||0),g.required?1:0)}" data-max="${Number(g.maxSelections||1)}"><legend>${esc(g.name)}</legend>${(g.options||[]).map(o=>`<label class="field"><span>${esc(o.name)}${optionDelta(o.priceDeltaCents)}</span><input data-option type="${g.selectionType==='SINGLE'?'radio':'checkbox'}" name="group-${esc(g.id)}" value="${esc(o.id)}"></label>`).join('')}</fieldset>`).join('');
    const combos=(cfg.combos||[]).map(g=>`<fieldset data-combo-group="${esc(g.id)}" data-min="${Number(g.minSelections||0)}" data-max="${Number(g.maxSelections||1)}"><legend>${esc(g.name)}</legend>${(g.items||[]).map(item=>`<label class="field"><span>${esc(item.productName)}${optionDelta(item.priceDeltaCents)}</span><input data-combo type="checkbox" data-group-id="${esc(g.id)}" data-product-id="${esc(item.productId)}"></label>`).join('')}</fieldset>`).join('');
    dialog.innerHTML=`<form method="dialog" id="mobile-product-config"><div class="section-head"><div><span class="eyebrow">PERSONALIZAR</span><h2>${esc(product.name)}</h2></div><button type="button" class="btn ghost" data-config-close>Fechar</button></div>${variants?`<fieldset><legend>Variação</legend>${variants}</fieldset>`:''}${groups}${combos}<label class="field">Observação<textarea name="note" maxlength="500" placeholder="Sem cebola, ponto da carne..."></textarea></label><div class="inline-error hidden" data-config-error></div><div class="actions"><button class="btn" type="submit">Adicionar ao pedido</button></div></form>`;
    document.body.appendChild(dialog);const form=dialog.querySelector('form');const fail=message=>{const node=dialog.querySelector('[data-config-error]');node.textContent=message;node.classList.remove('hidden');};
    dialog.querySelector('[data-config-close]').addEventListener('click',()=>dialog.close());
    form.addEventListener('submit',event=>{event.preventDefault();for(const group of form.querySelectorAll('[data-group],[data-combo-group]')){const selector=group.hasAttribute('data-group')?'[data-option]:checked':'[data-combo]:checked';const count=group.querySelectorAll(selector).length,min=Number(group.dataset.min||0),max=Number(group.dataset.max||1);if(count<min||count>max){fail(`Revise ${group.querySelector('legend')?.textContent||'as opções'}: escolha entre ${min} e ${max}.`);return;}}const fd=new FormData(form);cart.add({productId:product.id,name:product.name,unitPriceCents:product.salePriceCents,quantity:1,note:String(fd.get('note')||''),configuration:{variantId:String(fd.get('variantId')||'')||null,selections:[...form.querySelectorAll('[data-option]:checked')].map(input=>input.value),comboSelections:[...form.querySelectorAll('[data-combo]:checked')].map(input=>({groupId:input.dataset.groupId,productId:input.dataset.productId}))}});dialog.close();render();});
    dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();
  }
  function cartHtml(){const lines=cart.lines();const total=cart.summary().totalCents;return `<section class="panel order-composer"><div class="section-head"><div><span class="eyebrow">NOVO PEDIDO</span><h2>${lines.length?`${lines.length} ${lines.length===1?'item':'itens'}`:'Carrinho vazio'}</h2></div><strong class="composer-total">${money(total)}</strong></div>${lines.map(item=>`<div class="cart-line"><div><strong>${esc(item.name)}</strong><small>${item.note?esc(item.note)+' · ':''}${money(item.unitPriceCents)}</small></div><div class="qty"><button data-minus="${esc(item.id)}" aria-label="Diminuir">−</button><span>${item.quantity}</span><button data-plus="${esc(item.id)}" aria-label="Aumentar">+</button></div></div>`).join('')||'<div class="empty compact">Adicione itens do cardápio.</div>'}<div class="actions"><button id="send-order" class="btn" ${lines.length?'':'disabled'}>Enviar para a cozinha</button></div></section>`;}
  function bindProducts(list,sessionId,endpoint='/api/v1/mobile/orders'){root.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>{const p=list.find(x=>x.id===button.dataset.add);if(p)configureProduct(p);}));root.querySelectorAll('[data-minus]').forEach(button=>button.addEventListener('click',()=>{cart.changeQuantity(button.dataset.minus,-1);render();}));root.querySelectorAll('[data-plus]').forEach(button=>button.addEventListener('click',()=>{cart.changeQuantity(button.dataset.plus,1);render();}));document.getElementById('send-order')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Enviando…';try{const payload={items:cart.toOrderItems()};if(sessionId)payload.sessionId=sessionId;const result=await request(endpoint,{method:'POST',body:payload,mutation:true});cart.clear();const number=result?.order?.dailyNumber;notify(number?`Pedido enviado. Senha ${number}.`:'Pedido enviado para a cozinha.');await refresh();}catch(error){notify(error.message);button.disabled=false;button.textContent='Enviar para a cozinha';}});}
  function orderHistory(session){return (session?.orders||[]).slice().reverse().map(order=>`<div class="order-row"><div><strong>${order.items.map(i=>`${i.quantity}× ${esc(i.productName)}`).join(' · ')}</strong><small>${new Date(order.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><div>${status(order.status)}<strong>${money(order.totalCents)}</strong></div></div>`).join('')||'<div class="empty compact">Nenhum pedido lançado.</div>';}
  function renderTablet(){const {device,table,session,products:list}=context;shell(table?.label||device.name,'Tablet vinculado à mesa',`<div class="metric-grid"><div class="metric-card"><span>Conta atual</span><strong>${money(session?.totalCents||0)}</strong></div><div class="metric-card"><span>Pedidos</span><strong>${session?.orders?.length||0}</strong></div></div><section class="panel"><div class="section-head"><div><span class="eyebrow">COMANDA</span><h2>Pedidos da mesa</h2></div><div class="actions inline"><button id="call-waiter" class="btn ghost">Chamar garçom</button><button id="request-bill" class="btn warn">Pedir conta</button></div></div>${orderHistory(session)}</section>${session?`<div class="two-column">${cartHtml()}${products(list)}</div>`:'<section class="panel inline-error">A mesa ainda não possui comanda aberta. Solicite ao garçom.</section>'}`);document.getElementById('call-waiter')?.addEventListener('click',()=>service('WAITER'));document.getElementById('request-bill')?.addEventListener('click',()=>service('BILL'));if(session)bindProducts(list,session.id);}
  async function service(requestType){const button=requestType==='BILL'?document.getElementById('request-bill'):document.getElementById('call-waiter');if(button)button.disabled=true;try{await request('/api/v1/mobile/service',{method:'POST',body:{requestType},mutation:true});notify(requestType==='BILL'?'Conta solicitada.':'Garçom chamado.');await refresh();}catch(error){notify(error.message);if(button)button.disabled=false;}}
  function tableTone(table){return table.status==='FREE'?'free':table.status==='BILL_REQUESTED'?'attention':table.status==='CHECKOUT'?'attention':'occupied';}
  function renderWaiter(){const {device,tables,requests,products:list}=context;const selected=tables.find(t=>t.id===selectedTableId)||tables.find(t=>t.status!=='FREE')||tables[0];selectedTableId=selected?.id||'';const openRequests=requests||[];shell(device.name,'Salão · mesas, chamados e pedidos',`<div class="waiter-layout"><section class="panel floor-panel"><div class="section-head"><div><span class="eyebrow">SALÃO</span><h2>${tables.filter(t=>t.status!=='FREE').length} ocupadas de ${tables.length}</h2></div><span class="sync-note">Atualiza automaticamente</span></div><div class="table-grid">${tables.map(t=>`<button class="table-tile ${tableTone(t)} ${t.id===selectedTableId?'selected':''}" data-table="${esc(t.id)}"><span>${esc(t.label)}</span>${status(t.status)}<strong>${money(t.totalCents||0)}</strong></button>`).join('')}</div></section><aside class="panel request-panel"><div class="section-head"><div><span class="eyebrow">CHAMADOS</span><h2>${openRequests.length} pendentes</h2></div></div>${openRequests.map(r=>`<div class="request-row"><div><strong>${esc(r.tableLabel)}</strong><small>${r.requestType==='BILL'?'Pediu a conta':'Chamou o garçom'} · ${age(r.createdAt)}</small></div><button data-request="${esc(r.id)}">Atender</button></div>`).join('')||'<div class="empty compact">Nenhum chamado aberto.</div>'}</aside></div>${selected?`<section class="panel selected-table"><div class="section-head"><div><span class="eyebrow">MESA SELECIONADA</span><h2>${esc(selected.label)}</h2></div><div>${status(selected.status)}</div></div><div class="selected-summary"><div><span>Total</span><strong>${money(selected.totalCents||0)}</strong></div><div><span>Aberta</span><strong>${selected.openedAt?age(selected.openedAt):'—'}</strong></div></div><div class="actions">${selected.status==='FREE'?'<button id="open-table" class="btn">Abrir mesa</button>':'<span class="helper">Novo pedido disponível abaixo.</span>'}</div></section>`:''}${selected?.sessionId?`<div class="two-column">${cartHtml()}${products(list)}</div>`:''}`);root.querySelectorAll('[data-table]').forEach(b=>b.addEventListener('click',()=>{selectedTableId=b.dataset.table;cart.clear();renderWaiter();}));document.getElementById('open-table')?.addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await request(`/api/v1/mobile/tables/${encodeURIComponent(selected.id)}/open`,{method:'POST',body:{},mutation:true});notify('Mesa aberta.');await refresh();}catch(error){notify(error.message);event.currentTarget.disabled=false;}});root.querySelectorAll('[data-request]').forEach(b=>b.addEventListener('click',async()=>{try{b.disabled=true;await request(`/api/v1/mobile/requests/${encodeURIComponent(b.dataset.request)}`,{method:'PATCH',body:{status:'ACKNOWLEDGED'}});await refresh();}catch(error){notify(error.message);b.disabled=false;}}));if(selected?.sessionId)bindProducts(list,selected.sessionId);}
  function ticketCard(ticket){return `<article class="ticket-card ${esc(ticket.status)}"><header><div><span class="ticket-table">${esc(ticket.tableLabel)}</span><small>${esc(ticket.stationName)} · ${age(ticket.createdAt)}</small></div>${status(ticket.status)}</header><div class="ticket-items">${ticket.items.map(i=>`<div><strong>${i.quantity}× ${esc(i.productName)}</strong>${i.note?`<small>${esc(i.note)}</small>`:''}</div>`).join('')}</div><footer>${ticket.status==='NEW'?`<button class="btn" data-ticket="${esc(ticket.id)}" data-status="PREPARING">Iniciar preparo</button>`:''}${ticket.status==='PREPARING'?`<button class="btn secondary" data-ticket="${esc(ticket.id)}" data-status="READY">Marcar pronto</button>`:''}</footer></article>`;}
  function renderKitchen(){const {device,tickets}=context;const active=(tickets||[]).filter(t=>t.status!=='CANCELLED');const groups=[['NEW','Novos'],['PREPARING','Em preparo'],['READY','Prontos']];shell(device.name,'KDS local · produção por ordem de chegada',`<section class="kitchen-board">${groups.map(([key,label])=>`<div class="kitchen-lane"><header><div><span class="eyebrow">${esc(label.toUpperCase())}</span><h2>${active.filter(t=>t.status===key).length}</h2></div></header><div>${active.filter(t=>t.status===key).map(ticketCard).join('')||'<div class="empty lane-empty">Sem pedidos.</div>'}</div></div>`).join('')}</section>`);root.querySelectorAll('[data-ticket]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await request(`/api/v1/mobile/kitchen/tickets/${encodeURIComponent(b.dataset.ticket)}`,{method:'PATCH',body:{status:b.dataset.status}});await refresh();}catch(error){notify(error.message);b.disabled=false;}}));}
  function renderSelfService(){const {device,profile,table,session,products:list,paymentMode}=context;const location=profile.mode==='TABLE'?(table?.label||'Mesa'):'Retirada no balcão';const subtitle=profile.mode==='TABLE'?`Quiosque vinculado · ${location}`:'Quiosque · pedido para retirada';const info=profile.mode==='TABLE'?`<div class="metric-grid"><div class="metric-card"><span>Conta atual</span><strong>${money(session?.totalCents||0)}</strong></div><div class="metric-card"><span>Local</span><strong>${esc(location)}</strong></div></div>${session?'':'<section class="panel inline-error">Mesa sem comanda aberta. Solicite abertura no caixa.</section>'}`:`<section class="panel"><strong>Pagamento no atendimento</strong><p class="helper">${paymentMode==='MANUAL_AT_COUNTER'?'O pagamento é registrado manualmente no PDV.':'Pagamento externo.'}</p></section>`;shell(device.name,subtitle,`${info}${profile.mode==='TABLE'&&!session?'':`<div class="two-column">${cartHtml()}${products(list)}</div>`}`);if(profile.mode!=='TABLE'||session)bindProducts(list,profile.mode==='TABLE'?session.id:null,'/api/v1/mobile/self-service/orders');}
  function render(){if(!context)return login();const type=context.device?.deviceType;if(type==='TABLET')renderTablet();else if(type==='WAITER')renderWaiter();else if(type==='KITCHEN')renderKitchen();else if(type==='SELF_SERVICE')renderSelfService();else root.innerHTML='<section class="panel inline-error">Tipo de dispositivo não suportado.</section>';}
  document.getElementById('refresh')?.addEventListener('click',()=>refresh());
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&context)void refresh({quiet:true});});
  setInterval(()=>{if(document.visibilityState==='visible'&&context)void refresh({quiet:true});},15000);
  refresh().catch(()=>{});
})();
