'use strict';
const { randomBytes } = require('node:crypto');

class HttpError extends Error { constructor(statusCode, message) { super(message); this.statusCode = statusCode; } }
function sendJson(response, statusCode, payload, request, allowedOrigins = []) { const headers = { 'content-type':'application/json; charset=utf-8','cache-control':'no-store' }; const origin=request?.headers?.origin; if(origin&&allowedOrigins.includes(origin)){headers['access-control-allow-origin']=origin;headers.vary='Origin';} response.writeHead(statusCode,headers); response.end(JSON.stringify(payload)); }
function sendBinary(response,payload,request){const etag=`"${payload.sha256}"`;if(request.headers['if-none-match']===etag){response.writeHead(304,{etag,'cache-control':'private, max-age=86400'});response.end();return;}response.writeHead(200,{'content-type':payload.mimeType,'content-length':payload.bytes.length,'cache-control':'private, max-age=86400, immutable',etag,'x-photo-version':String(payload.version)});response.end(payload.bytes);}
async function readJson(request, limit) { let total=0;const chunks=[];for await(const chunk of request){total+=chunk.length;if(total>limit)throw new HttpError(413,'Corpo da requisicao excede o limite permitido.');chunks.push(chunk);}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw new HttpError(400,'JSON invalido.');} }
function bearer(request){const value=String(request.headers.authorization||'');return value.startsWith('Bearer ')?value.slice(7).trim():'';}
function queryFilters(url, names){const result={};for(const name of names){const value=url.searchParams.get(name);if(value!==null&&value!=='')result[name]=value;}return result;}
function publicDiagnostic(result){if(!result)return result;const {filePath,...safe}=result;return safe;}

function createRouter({runtime,installationToken='',bodyLimitBytes=1024*1024,allowedOrigins=[],sessionTtlMs=12*60*60*1000,requireTerminalAuth=false,sessionStore=null}={}){
  if(!runtime)throw new TypeError('runtime is required.');
  const sessions=sessionStore||new Map();
  function authenticate(request){
    const token=bearer(request);const session=sessions.get(token);
    if(!session||session.expiresAt<=Date.now()){if(token)sessions.delete(token);throw new HttpError(401,'Sessao invalida ou expirada.');}
    if(requireTerminalAuth){const terminal=runtime.terminals.listTerminals().find(item=>item.terminalId===session.terminalId);if(!terminal||terminal.status!=='ACTIVE')throw new HttpError(401,'Terminal nao autorizado.');}
    return session;
  }
  function requireRole(session,roles){if(!roles.includes(session.role))throw new HttpError(403,'Permissao insuficiente.');}
  function actor(session){return{userId:session.userId,role:session.role,terminalId:session.terminalId||null};}
  function checkInstallToken(request){if(installationToken&&request.headers['x-pdv-token']!==installationToken)throw new HttpError(401,'Token de instalacao invalido.');}
  async function dispatch(){return runtime.dispatchPending();}
  async function mutation(request,pathname,statusCode,handler){const mutationId=String(request.headers['x-mutation-id']||'').trim();if(!mutationId||!runtime.mutations)return{statusCode,payload:await handler(mutationId||null)};return runtime.mutations.execute({mutationId,method:request.method,path:pathname},async()=>({statusCode,payload:await handler(mutationId)}));}

  return async function route(request,response){
    try{
      const url=new URL(request.url||'/',`http://${request.headers.host||'localhost'}`);const pathname=url.pathname;
      if(request.method==='OPTIONS'){sendJson(response,204,{},request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/health'){sendJson(response,200,{ok:true,status:'ready',schemaVersion:runtime.db.prepare('SELECT MAX(version) AS version FROM schema_migrations').get().version},request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/lan/handshake'){sendJson(response,200,runtime.terminals.handshake({terminalId:url.searchParams.get('terminalId'),appVersion:url.searchParams.get('appVersion')||'0.0.0'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/lan/pair'){const body=await readJson(request,bodyLimitBytes);const paired=runtime.terminals.pairTerminal(body);sendJson(response,201,paired,request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/setup/status'){sendJson(response,200,{needsSetup:runtime.catalog.countUsers()===0},request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/setup/admin'){checkInstallToken(request);if(runtime.catalog.countUsers()!==0)throw new HttpError(409,'Configuracao inicial ja concluida.');const body=await readJson(request,bodyLimitBytes);const user=runtime.catalog.createUser({...body,role:'admin',active:true},{userId:'setup',role:'system',terminalId:null});sendJson(response,201,user,request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/auth/login'){
        const body=await readJson(request,bodyLimitBytes);let terminalId=String(body.terminalId||'').trim()||null;
        if(requireTerminalAuth){const headerId=String(request.headers['x-terminal-id']||'').trim();const terminalKey=String(request.headers['x-terminal-key']||'');const terminalAuth=runtime.terminals.authenticateTerminal(headerId,terminalKey);if(!terminalAuth.ok)throw new HttpError(401,'Terminal nao autorizado.');if(terminalId&&terminalId!==headerId)throw new HttpError(401,'Identidade do terminal divergente.');const hs=runtime.terminals.handshake({terminalId:headerId,appVersion:terminalAuth.terminal.appVersion});if(!hs.compatible)throw new HttpError(426,'Versao do terminal incompativel.');terminalId=headerId;}else checkInstallToken(request);
        const auth=runtime.catalog.verifyUserPassword(body.username,body.password);if(!auth.ok)throw new HttpError(401,'Usuario ou senha invalidos.');const sessionToken=randomBytes(32).toString('hex');const session={userId:auth.user.id,role:auth.user.role,name:auth.user.name,terminalId,expiresAt:Date.now()+sessionTtlMs};sessions.set(sessionToken,session);sendJson(response,200,{sessionToken,user:auth.user,terminalId,expiresAt:new Date(session.expiresAt).toISOString()},request,allowedOrigins);return;
      }

      const session=authenticate(request);const currentActor=actor(session);const mutationId=String(request.headers['x-mutation-id']||'').trim()||null;

      if(request.method==='POST'&&pathname==='/api/v1/lan/pairing-codes'){requireRole(session,['admin']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.terminals.createPairingCode({createdBy:session.userId,ttlSeconds:body.ttlSeconds}),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/terminals'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.terminals.listTerminals(),request,allowedOrigins);return;}
      const terminalMatch=pathname.match(/^\/api\/v1\/terminals\/([^/]+)$/);if(request.method==='PATCH'&&terminalMatch){requireRole(session,['admin']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.terminals.setTerminalStatus(decodeURIComponent(terminalMatch[1]),body.status),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/backups/status'){requireRole(session,['admin','manager']);if(!runtime.backups)throw new HttpError(409,'Backup requer banco persistente.');sendJson(response,200,runtime.backups.getBackupStatus(),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/backups'){requireRole(session,['admin','manager']);if(!runtime.backups)throw new HttpError(409,'Backup requer banco persistente.');sendJson(response,200,runtime.backups.listBackups(),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/backups'){requireRole(session,['admin']);if(!runtime.backups)throw new HttpError(409,'Backup requer banco persistente.');const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.backups.createBackup(body.reason||'manual'),request,allowedOrigins);return;}
      const backupValidate=pathname.match(/^\/api\/v1\/backups\/([^/]+)\/validate$/);if(request.method==='POST'&&backupValidate){requireRole(session,['admin','manager']);sendJson(response,200,runtime.backups.validateBackup(decodeURIComponent(backupValidate[1])),request,allowedOrigins);return;}
      const backupRestore=pathname.match(/^\/api\/v1\/backups\/([^/]+)\/restore$/);if(request.method==='POST'&&backupRestore){requireRole(session,['admin']);sendJson(response,202,runtime.backups.prepareRestore(decodeURIComponent(backupRestore[1]),{actor:currentActor}),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/settings'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.settings.list({scope:url.searchParams.get('scope')||null,prefix:url.searchParams.get('prefix')||''}),request,allowedOrigins);return;}
      const settingMatch=pathname.match(/^\/api\/v1\/settings\/([^/]+)$/);if(request.method==='PUT'&&settingMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.settings.set(decodeURIComponent(settingMatch[1]),body.value,{scope:body.scope||'global',actor:currentActor}),request,allowedOrigins);return;}if(request.method==='DELETE'&&settingMatch){sendJson(response,200,{removed:runtime.settings.remove(decodeURIComponent(settingMatch[1]),{scope:url.searchParams.get('scope')||'global',actor:currentActor})},request,allowedOrigins);return;}

      if(request.method==='POST'&&pathname==='/api/v1/imports/preview'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.imports.preview(body),request,allowedOrigins);return;}
      const importCommit=pathname.match(/^\/api\/v1\/imports\/([^/]+)\/commit$/);if(request.method==='POST'&&importCommit){requireRole(session,['admin','manager']);sendJson(response,200,runtime.imports.commit(decodeURIComponent(importCommit[1]),{actor:currentActor}),request,allowedOrigins);return;}
      const importGet=pathname.match(/^\/api\/v1\/imports\/([^/]+)$/);if(request.method==='GET'&&importGet){requireRole(session,['admin','manager']);const batch=runtime.imports.getBatch(decodeURIComponent(importGet[1]));if(!batch)throw new HttpError(404,'Lote de importacao nao encontrado.');sendJson(response,200,batch,request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/audit'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.health.listAudit(queryFilters(url,['actorId','actorRole','entity','action','entityId','from','to','limit'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/system/health'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.health.snapshot(),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/system/logs'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.logger.list(queryFilters(url,['level','subsystem','terminalId','correlationId','from','to','limit'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/system/diagnostics'){requireRole(session,['admin']);if(!runtime.diagnostics)throw new HttpError(409,'Diagnostico requer banco persistente.');sendJson(response,201,publicDiagnostic(runtime.diagnostics.createPackage({actor:currentActor})),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/pilot/readiness'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.pilot.readiness(),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/pilot'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.pilot.listChecks(),request,allowedOrigins);return;}
      const pilotMatch=pathname.match(/^\/api\/v1\/pilot\/([^/]+)$/);if(request.method==='PATCH'&&pilotMatch){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.pilot.updateCheck(decodeURIComponent(pilotMatch[1]),{...body,actor:currentActor}),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/categories'){sendJson(response,200,runtime.catalog.listCategories({includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/categories'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.catalog.upsertCategory(body,currentActor),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/products'){sendJson(response,200,runtime.catalog.listProducts({includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/products'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.catalog.upsertProduct(body,currentActor),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/product-photos/manifest'){sendJson(response,200,runtime.productPhotos.manifest(),request,allowedOrigins);return;}
      const photoFileMatch=pathname.match(/^\/api\/v1\/product-photos\/([^/]+)\/(original|thumbnail)$/);if(request.method==='GET'&&photoFileMatch){sendBinary(response,runtime.productPhotos.read(decodeURIComponent(photoFileMatch[1]),photoFileMatch[2]),request);return;}
      const photoMatch=pathname.match(/^\/api\/v1\/product-photos\/([^/]+)$/);if(request.method==='POST'&&photoMatch){requireRole(session,['admin','manager']);const body=await readJson(request,16*1024*1024);sendJson(response,201,runtime.productPhotos.save({...body,productId:decodeURIComponent(photoMatch[1])},currentActor),request,allowedOrigins);return;}if(request.method==='DELETE'&&photoMatch){requireRole(session,['admin','manager']);sendJson(response,200,runtime.productPhotos.remove(decodeURIComponent(photoMatch[1]),currentActor),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/customers'){sendJson(response,200,runtime.catalog.listCustomers({includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/customers'){const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.catalog.upsertCustomer(body,currentActor),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/users'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.catalog.listUsers({includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/sellers'){requireRole(session,['admin','manager','cashier']);sendJson(response,200,runtime.catalog.listUsers().filter(user=>['cashier','manager','admin'].includes(user.role)),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/users'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.catalog.upsertUser(body,currentActor),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/inventory'){sendJson(response,200,runtime.inventory.listBalances({query:url.searchParams.get('query')||''}),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/inventory/low-stock'){sendJson(response,200,runtime.inventory.listLowStock(),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/inventory/movements'){sendJson(response,200,runtime.inventory.listMovements(queryFilters(url,['productId','type','from','to'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/inventory/movements'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.inventory.move(body,currentActor),request,allowedOrigins);return;}
      const inventoryMatch=pathname.match(/^\/api\/v1\/inventory\/([^/]+)$/);if(request.method==='GET'&&inventoryMatch){const productId=decodeURIComponent(inventoryMatch[1]);sendJson(response,200,{productId,quantity:runtime.inventory.getBalance(productId)},request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/cash/sessions'){sendJson(response,200,runtime.cash.listSessions(queryFilters(url,['terminalId','operatorId','status','from','to'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/cash/sessions'){const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,201,async mid=>{const opened=runtime.cash.openSession({...body,operatorId:session.userId,terminalId:session.terminalId||body.terminalId,actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{session:opened,dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/cash/open'){const terminalId=url.searchParams.get('terminalId')||session.terminalId;if(!terminalId)throw new HttpError(400,'terminalId obrigatorio.');sendJson(response,200,runtime.cash.getOpenSession(terminalId),request,allowedOrigins);return;}
      const cashMovementsMatch=pathname.match(/^\/api\/v1\/cash\/sessions\/([^/]+)\/movements$/);if(request.method==='GET'&&cashMovementsMatch){sendJson(response,200,runtime.cash.listSessionMovements(decodeURIComponent(cashMovementsMatch[1])),request,allowedOrigins);return;}
      const cashMatch=pathname.match(/^\/api\/v1\/cash\/sessions\/([^/]+)\/(supply|withdraw|close)$/);if(request.method==='POST'&&cashMatch){const id=decodeURIComponent(cashMatch[1]);const action=cashMatch[2];const body=await readJson(request,bodyLimitBytes);let result;if(action==='supply')result=runtime.cash.addSupply(id,{...body,actor:currentActor});else if(action==='withdraw')result=runtime.cash.withdraw(id,{...body,actor:currentActor});else result=runtime.cash.closeSession(id,{...body,actor:currentActor,mutationId});const dispatchResult=action==='close'?await dispatch():null;sendJson(response,200,dispatchResult?{session:result,dispatch:dispatchResult}:result,request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/sales/history'){sendJson(response,200,runtime.sales.listHistory(queryFilters(url,['from','to','operatorId','sellerId','customerId','status','query','limit','offset'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/sales'){sendJson(response,200,runtime.sales.listSales({status:url.searchParams.get('status'),limit:url.searchParams.get('limit')}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/sales'){const body=await readJson(request,bodyLimitBytes);const sale=runtime.sales.openSale({...body,operatorId:session.userId,terminalId:session.terminalId||body.terminalId},currentActor);sendJson(response,201,sale,request,allowedOrigins);return;}
      const saleDetailsMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/details$/);if(request.method==='GET'&&saleDetailsMatch){const sale=runtime.sales.getSaleDetails(decodeURIComponent(saleDetailsMatch[1]));if(!sale)throw new HttpError(404,'Venda nao encontrada.');sendJson(response,200,sale,request,allowedOrigins);return;}
      const customerMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/customer$/);if(request.method==='POST'&&customerMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.setCustomer(decodeURIComponent(customerMatch[1]),body.customerId),request,allowedOrigins);return;}
      const sellerMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/seller$/);if(request.method==='POST'&&sellerMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.setSeller(decodeURIComponent(sellerMatch[1]),body.sellerId,currentActor),request,allowedOrigins);return;}
      const itemListMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/items$/);if(request.method==='POST'&&itemListMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.addItem(decodeURIComponent(itemListMatch[1]),body),request,allowedOrigins);return;}
      const itemPriceMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/items\/([^/]+)\/price$/);if(request.method==='PUT'&&itemPriceMatch){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.overrideItemPrice(decodeURIComponent(itemPriceMatch[1]),decodeURIComponent(itemPriceMatch[2]),{unitPriceCents:body.unitPriceCents,reason:body.reason,actor:currentActor}),request,allowedOrigins);return;}
      const itemMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/items\/([^/]+)$/);if(request.method==='PUT'&&itemMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.updateItemQuantity(decodeURIComponent(itemMatch[1]),decodeURIComponent(itemMatch[2]),body.quantity),request,allowedOrigins);return;}if(request.method==='DELETE'&&itemMatch){sendJson(response,200,runtime.sales.removeItem(decodeURIComponent(itemMatch[1]),decodeURIComponent(itemMatch[2])),request,allowedOrigins);return;}
      const discountMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/discount$/);if(request.method==='POST'&&discountMatch){const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.sales.applyDiscount(decodeURIComponent(discountMatch[1]),{discountCents:body.discountCents}),request,allowedOrigins);return;}
      const suspendMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/suspend$/);if(request.method==='POST'&&suspendMatch){sendJson(response,200,runtime.sales.suspendSale(decodeURIComponent(suspendMatch[1])),request,allowedOrigins);return;}
      const resumeMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/resume$/);if(request.method==='POST'&&resumeMatch){sendJson(response,200,runtime.sales.resumeSale(decodeURIComponent(resumeMatch[1])),request,allowedOrigins);return;}
      const completeMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/complete$/);if(request.method==='POST'&&completeMatch){const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,200,async mid=>{const sale=runtime.sales.completeSale(decodeURIComponent(completeMatch[1]),{payments:body.payments||[],actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{sale,dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const cancelMatch=pathname.match(/^\/api\/v1\/sales\/([^/]+)\/cancel$/);if(request.method==='POST'&&cancelMatch){const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,200,async mid=>{const sale=runtime.sales.cancelSale(decodeURIComponent(cancelMatch[1]),{reason:body.reason,actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{sale,dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const saleGet=pathname.match(/^\/api\/v1\/sales\/([^/]+)$/);if(request.method==='GET'&&saleGet){const sale=runtime.sales.getSale(decodeURIComponent(saleGet[1]));if(!sale)throw new HttpError(404,'Venda nao encontrada.');sendJson(response,200,sale,request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/returns'){sendJson(response,200,runtime.returns.listReturns(queryFilters(url,['saleId','status','from','to'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/returns'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,201,async mid=>{const ret=runtime.returns.createReturn({...body,terminalId:session.terminalId||body.terminalId,operatorId:session.userId,actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{return:ret,dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const returnCancel=pathname.match(/^\/api\/v1\/returns\/([^/]+)\/cancel$/);if(request.method==='POST'&&returnCancel){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,200,async mid=>{const ret=runtime.returns.cancelReturn(decodeURIComponent(returnCancel[1]),{reason:body.reason,actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{return:ret,dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const returnGet=pathname.match(/^\/api\/v1\/returns\/([^/]+)$/);if(request.method==='GET'&&returnGet){const ret=runtime.returns.getReturn(decodeURIComponent(returnGet[1]));if(!ret)throw new HttpError(404,'Devolucao nao encontrada.');sendJson(response,200,ret,request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/finance/accounts'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.finance.listAccounts({includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/finance/accounts'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.finance.createAccount(body,currentActor),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/finance/summary'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.finance.getSummary(queryFilters(url,['from','to','asOf'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/finance/entries'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.finance.listEntries(queryFilters(url,['kind','status','from','to','accountId','query','asOf'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/finance/entries'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.finance.createEntry(body,currentActor),request,allowedOrigins);return;}
      const financeSettle=pathname.match(/^\/api\/v1\/finance\/entries\/([^/]+)\/settle$/);if(request.method==='POST'&&financeSettle){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.finance.settleEntry(decodeURIComponent(financeSettle[1]),body,currentActor),request,allowedOrigins);return;}
      const financeCancel=pathname.match(/^\/api\/v1\/finance\/entries\/([^/]+)\/cancel$/);if(request.method==='POST'&&financeCancel){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.finance.cancelEntry(decodeURIComponent(financeCancel[1]),{reason:body.reason,actor:currentActor}),request,allowedOrigins);return;}
      const settlementReverse=pathname.match(/^\/api\/v1\/finance\/settlements\/([^/]+)\/reverse$/);if(request.method==='POST'&&settlementReverse){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,200,runtime.finance.reverseSettlement(decodeURIComponent(settlementReverse[1]),{reason:body.reason,actor:currentActor}),request,allowedOrigins);return;}
      const financeGet=pathname.match(/^\/api\/v1\/finance\/entries\/([^/]+)$/);if(request.method==='GET'&&financeGet){requireRole(session,['admin','manager']);const entry=runtime.finance.getEntry(decodeURIComponent(financeGet[1]));if(!entry)throw new HttpError(404,'Lancamento financeiro nao encontrado.');sendJson(response,200,entry,request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/reports/sales'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.reports.buildSalesSummary(queryFilters(url,['from','to','sellerId'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/reports/inventory'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.reports.buildInventorySummary(),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/reports/cash'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.reports.buildCashSummary(queryFilters(url,['from','to'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/reports/finance'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.reports.buildFinanceSummary(queryFilters(url,['from','to','asOf'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/reports/sales.csv'){requireRole(session,['admin','manager']);sendJson(response,200,{csv:runtime.reports.exportSalesCsv(queryFilters(url,['from','to','sellerId']))},request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/commissions'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.commissions.report(queryFilters(url,['from','to','sellerId'])),request,allowedOrigins);return;}
      if(request.method==='GET'&&pathname==='/api/v1/commission-rules'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.commissions.listRules({sellerId:url.searchParams.get('sellerId')||null,includeInactive:url.searchParams.get('includeInactive')==='true'}),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/commission-rules'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.commissions.upsertRule(body,currentActor),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/commission-payments'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);sendJson(response,201,runtime.commissions.pay(body,currentActor),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/print/jobs'){sendJson(response,200,runtime.printing.listJobs(queryFilters(url,['status','type','entityType','entityId'])),request,allowedOrigins);return;}
      const printRetry=pathname.match(/^\/api\/v1\/print\/jobs\/([^/]+)\/retry$/);if(request.method==='POST'&&printRetry){sendJson(response,200,runtime.printing.retryJob(decodeURIComponent(printRetry[1])),request,allowedOrigins);return;}
      const printReprint=pathname.match(/^\/api\/v1\/print\/jobs\/([^/]+)\/reprint$/);if(request.method==='POST'&&printReprint){sendJson(response,201,runtime.printing.reprint(decodeURIComponent(printReprint[1])),request,allowedOrigins);return;}

      if(request.method==='GET'&&pathname==='/api/v1/fiscal/documents'){requireRole(session,['admin','manager']);sendJson(response,200,runtime.fiscal.listDocuments(queryFilters(url,['saleId','status','documentType','environment'])),request,allowedOrigins);return;}
      if(request.method==='POST'&&pathname==='/api/v1/fiscal/documents'){requireRole(session,['admin','manager']);const body=await readJson(request,bodyLimitBytes);const result=await mutation(request,pathname,201,async mid=>{const doc=runtime.fiscal.requestIssue({...body,actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{document:runtime.fiscal.getDocument(doc.id),dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const fiscalRetry=pathname.match(/^\/api\/v1\/fiscal\/documents\/([^/]+)\/retry$/);if(request.method==='POST'&&fiscalRetry){requireRole(session,['admin','manager']);const result=await mutation(request,pathname,200,async mid=>{runtime.fiscal.retryIssue(decodeURIComponent(fiscalRetry[1]),{actor:currentActor,mutationId:mid});const dispatchResult=await dispatch();return{document:runtime.fiscal.getDocument(decodeURIComponent(fiscalRetry[1])),dispatch:dispatchResult};});sendJson(response,result.statusCode,result.payload,request,allowedOrigins);return;}
      const fiscalGet=pathname.match(/^\/api\/v1\/fiscal\/documents\/([^/]+)$/);if(request.method==='GET'&&fiscalGet){requireRole(session,['admin','manager']);const doc=runtime.fiscal.getDocument(decodeURIComponent(fiscalGet[1]));if(!doc)throw new HttpError(404,'Documento fiscal nao encontrado.');sendJson(response,200,doc,request,allowedOrigins);return;}

      throw new HttpError(404,'Rota nao encontrada.');
    }catch(error){let status=error.statusCode||400;if(/UNIQUE constraint failed/.test(error.message||''))status=409;try{runtime.logger?.log({level:status>=500?'error':'warn',subsystem:'http',message:error.message||'Erro interno.',correlationId:String(request.headers['x-mutation-id']||'')||null,context:{method:request.method,url:request.url,status}});}catch{}sendJson(response,status,{error:error.message||'Erro interno.'},request,allowedOrigins);}
  };
}
module.exports={HttpError,readJson,createRouter};