'use strict';

(()=>{
  const ApiClient=window.PdvApiClient?.ApiClient;if(!ApiClient)return;const api=new ApiClient();const e=encodeURIComponent;
  const FINAL_MODULES=new Set(['RETAIL','SERVICES','WORKSHOP','SELF_SERVICE']);
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const money=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  function content(){return document.getElementById('route-content');}
  function notify(message,error=false){const root=document.getElementById('toast-root');if(!root)return;const node=document.createElement('div');node.className=`toast ${error?'error':'success'}`;node.textContent=message;root.appendChild(node);setTimeout(()=>node.remove(),3200);}
  function back(){return '<button type="button" class="secondary-button" id="vertical-back">← Configurações</button>';}
  function bindBack(){document.getElementById('vertical-back')?.addEventListener('click',()=>window.PdvOperationalUi?.showRoute?.('settings'));}
  function field(name,label,type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" type="${type}" ${extra}></label>`;}
  async function req(path,options){return api.request(path,options);}

  async function renderRetail(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Varejo</h1><p>Variantes, SKU/código e estoque individual reutilizando o catálogo E40.</p></div>${back()}</header><div class="data-card"><form id="retail-search" class="vertical-form">${field('query','Buscar produto, variante, SKU ou código')}<button class="primary-button">Buscar</button></form><div id="retail-results"></div></div><div class="data-card"><h2>Adicionar variante a uma venda aberta</h2><form id="retail-sale" class="vertical-form">${field('saleId','ID da venda')}${field('variantId','ID da variante')}${field('quantity','Quantidade','number','min="0.001" step="0.001" value="1"')}<button class="primary-button">Adicionar</button></form></div></section>`;bindBack();
    async function search(query=''){try{const rows=await req(`/api/v1/vertical/retail/variants?query=${e(query)}`);document.getElementById('retail-results').innerHTML=rows.map(row=>`<div class="vertical-row"><div><strong>${esc(row.productName)} · ${esc(row.name)}</strong><span>${esc(row.sku||row.barcode||'Sem SKU')} · ${money(row.unitPriceCents)}</span></div><form data-stock="${esc(row.variantId)}" class="vertical-actions"><input name="quantity" type="number" min="0" step="0.001" value="${Number(row.quantity)}"><button>Salvar estoque</button></form></div>`).join('')||'<p class="vertical-empty">Nenhuma variante encontrada.</p>';root.querySelectorAll('[data-stock]').forEach(form=>form.addEventListener('submit',async event=>{event.preventDefault();try{await req(`/api/v1/vertical/retail/variants/${e(form.dataset.stock)}/stock`,{method:'PUT',body:{quantity:Number(new FormData(form).get('quantity'))}});notify('Estoque da variante atualizado.');await search(query);}catch(error){notify(error.message,true);}}));}catch(error){notify(error.message,true);}}
    document.getElementById('retail-search').addEventListener('submit',event=>{event.preventDefault();search(new FormData(event.currentTarget).get('query'));});
    document.getElementById('retail-sale').addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await req(`/api/v1/vertical/retail/sales/${e(data.get('saleId'))}/variant`,{method:'POST',body:{variantId:data.get('variantId'),quantity:Number(data.get('quantity'))}});notify('Variante adicionada à venda canônica.');}catch(error){notify(error.message,true);}});await search('');
  }

  function renderServices(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Serviços</h1><p>Catálogo, profissionais, agenda local e comissão.</p></div>${back()}</header><div class="vertical-layout"><section class="data-card"><h2>Serviço</h2><form id="service-form" class="vertical-form">${field('id','ID')}${field('name','Nome')}${field('durationMinutes','Duração (min)','number','min="1"')}${field('price','Preço (R$)')}<button class="primary-button">Salvar serviço</button></form></section><section class="data-card"><h2>Profissional</h2><form id="professional-form" class="vertical-form">${field('id','ID')}${field('name','Nome')}${field('commission','Comissão (%)','number','min="0" max="100" step="0.01"')}<button class="primary-button">Salvar profissional</button></form></section></div><div class="data-card"><h2>Vínculo e agenda</h2><form id="link-form" class="vertical-form">${field('serviceId','ID serviço')}${field('professionalId','ID profissional')}${field('commission','Comissão (%)','number','min="0" max="100" step="0.01"')}<button>Vincular</button></form><form id="appointment-form" class="vertical-form">${field('serviceId','ID serviço')}${field('professionalId','ID profissional')}${field('customerId','ID cliente')}${field('startsAt','Início','datetime-local')}<button class="primary-button">Agendar</button></form></div><div class="data-card"><h2>Comissões concluídas</h2><button id="commission-refresh" class="secondary-button">Atualizar relatório</button><pre id="commission-output" class="vertical-output"></pre></div></section>`;bindBack();
    document.getElementById('service-form').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{await req('/api/v1/vertical/services/catalog',{method:'POST',body:{id:d.get('id'),name:d.get('name'),durationMinutes:Number(d.get('durationMinutes')),priceCents:Math.round(Number(String(d.get('price')).replace(',','.'))*100)}});notify('Serviço salvo.');}catch(error){notify(error.message,true);}});
    document.getElementById('professional-form').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{await req('/api/v1/vertical/services/professionals',{method:'POST',body:{id:d.get('id'),name:d.get('name'),defaultCommissionBps:Math.round(Number(d.get('commission'))*100)}});notify('Profissional salvo.');}catch(error){notify(error.message,true);}});
    document.getElementById('link-form').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{await req(`/api/v1/vertical/services/catalog/${e(d.get('serviceId'))}/professionals/${e(d.get('professionalId'))}`,{method:'PUT',body:{commissionBps:Math.round(Number(d.get('commission'))*100)}});notify('Vínculo salvo.');}catch(error){notify(error.message,true);}});
    document.getElementById('appointment-form').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{const starts=new Date(d.get('startsAt')).toISOString();await req('/api/v1/vertical/services/appointments',{method:'POST',body:{serviceId:d.get('serviceId'),professionalId:d.get('professionalId'),customerId:d.get('customerId')||null,startsAt:starts},mutationId:api.mutationId()});notify('Atendimento agendado.');}catch(error){notify(error.message,true);}});
    document.getElementById('commission-refresh').addEventListener('click',async()=>{try{const report=await req('/api/v1/vertical/services/commissions');document.getElementById('commission-output').textContent=`Base: ${money(report.totalServiceCents)}\nComissão: ${money(report.totalCommissionCents)}`;}catch(error){notify(error.message,true);}});
  }

  function renderWorkshop(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Oficina</h1><p>OS com bem/veículo, diagnóstico, orçamento, aprovação e venda canônica.</p></div>${back()}</header><div class="vertical-layout"><section class="data-card"><h2>Veículo/equipamento</h2><form id="asset-form" class="vertical-form">${field('id','ID')}${field('customerId','ID cliente')}<label class="field"><span>Tipo</span><select name="kind"><option value="VEHICLE">Veículo</option><option value="EQUIPMENT">Equipamento</option></select></label>${field('identifier','Placa/identificador')}${field('make','Marca')}${field('model','Modelo')}<button class="primary-button">Salvar</button></form></section><section class="data-card"><h2>Nova OS</h2><form id="work-form" class="vertical-form">${field('id','ID OS')}${field('customerId','ID cliente')}${field('assetId','ID veículo/equipamento')}${field('complaint','Queixa')}<button class="primary-button">Abrir OS</button></form></section></div><div class="data-card"><h2>Consultar OS</h2><form id="work-get" class="vertical-form">${field('id','ID OS')}<button>Consultar</button></form><pre id="work-output" class="vertical-output"></pre></div></section>`;bindBack();
    document.getElementById('asset-form').addEventListener('submit',async event=>{event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));try{await req('/api/v1/vertical/workshop/assets',{method:'POST',body:d});notify('Bem salvo.');}catch(error){notify(error.message,true);}});
    document.getElementById('work-form').addEventListener('submit',async event=>{event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));try{await req('/api/v1/vertical/workshop/orders',{method:'POST',body:d,mutationId:api.mutationId()});notify('OS aberta.');}catch(error){notify(error.message,true);}});
    document.getElementById('work-get').addEventListener('submit',async event=>{event.preventDefault();const id=new FormData(event.currentTarget).get('id');try{const order=await req(`/api/v1/vertical/workshop/orders/${e(id)}`);document.getElementById('work-output').textContent=`Status: ${order.status}\nTotal: ${money(order.totalCents)}\nItens: ${order.items.length}\nVenda: ${order.saleId||'-'}`;}catch(error){notify(error.message,true);}});
  }

  function renderSelfService(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Autoatendimento</h1><p>Dispositivo pareado, sem acesso a caixa, relatórios ou administração.</p></div>${back()}</header><div class="data-card"><form id="self-create" class="vertical-form">${field('name','Nome do dispositivo')}<label class="field"><span>Modo</span><select name="mode"><option value="PICKUP">Retirada</option><option value="TABLE">Mesa fixa</option></select></label>${field('tableId','ID da mesa (modo mesa)')}${field('operatorId','ID do operador local (retirada)')}<button class="primary-button">Criar e configurar</button></form><pre id="self-output" class="vertical-output"></pre></div><div class="data-card"><button id="self-access" class="secondary-button">Exibir QR de acesso local</button></div></section>`;bindBack();
    document.getElementById('self-create').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{const device=await req('/api/v1/restaurant/devices',{method:'POST',body:{name:d.get('name'),deviceType:'SELF_SERVICE'}});const profile=await req(`/api/v1/vertical/self-service/devices/${e(device.id)}`,{method:'PUT',body:{mode:d.get('mode'),tableId:d.get('tableId')||null,operatorId:d.get('operatorId')||null}});document.getElementById('self-output').textContent=`ID: ${device.id}\nChave: ${device.credential}\nModo: ${profile.mode}\nGuarde a chave no dispositivo; ela não é exibida novamente.`;notify('Autoatendimento configurado.');}catch(error){notify(error.message,true);}});
    document.getElementById('self-access').addEventListener('click',renderMobileAccess);
  }

  function renderMobileAccess(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Acesso mobile local</h1><p>QR gerado localmente. HTTP somente em LAN confiável; não é PWA.</p></div>${back()}</header><div class="data-card"><form id="access-form" class="vertical-form">${field('host','IP/host do servidor','text','value="127.0.0.1"')}${field('port','Porta','number','value="4174"')}<button class="primary-button">Gerar QR</button></form><div id="access-output"></div></div></section>`;bindBack();document.getElementById('access-form').addEventListener('submit',async event=>{event.preventDefault();const d=new FormData(event.currentTarget);try{const result=await req(`/api/v1/vertical/mobile-access?host=${e(d.get('host'))}&port=${e(d.get('port'))}&path=${e('/mobile')}`);document.getElementById('access-output').innerHTML=`<p><strong>${esc(result.url)}</strong></p><div style="max-width:260px">${result.qrSvg}</div><p class="vertical-rule">${esc(result.warning)}</p>`;}catch(error){notify(error.message,true);}});}

  async function renderHardware(){
    const root=content();root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Periféricos</h1><p>Diagnóstico e testes locais. Teste de software não equivale à homologação física de um modelo.</p></div>${back()}</header><div class="data-card"><div class="vertical-actions"><button id="hw-refresh">Diagnóstico</button><button id="hw-printer">Testar impressora NÃO FISCAL</button><button id="hw-scale">Ler balança</button><button id="hw-drawer">Abrir gaveta</button></div><pre id="hw-output" class="vertical-output"></pre></div></section>`;bindBack();const out=document.getElementById('hw-output');async function run(fn){try{out.textContent=JSON.stringify(await fn(),null,2);}catch(error){out.textContent=error.message;notify(error.message,true);}}document.getElementById('hw-refresh').addEventListener('click',()=>run(()=>window.artisysDesktop.hardware.diagnostics()));document.getElementById('hw-printer').addEventListener('click',()=>run(()=>window.artisysDesktop.hardware.testPrinter('TESTE ARTISYS\nDOCUMENTO NAO FISCAL\n')));document.getElementById('hw-scale').addEventListener('click',()=>run(()=>window.artisysDesktop.hardware.testScale()));document.getElementById('hw-drawer').addEventListener('click',()=>run(()=>window.artisysDesktop.hardware.testDrawer()));await run(()=>window.artisysDesktop.hardware.diagnostics());
  }

  function renderFinalModule(id){if(id==='RETAIL')return renderRetail();if(id==='SERVICES')return renderServices();if(id==='WORKSHOP')return renderWorkshop();if(id==='SELF_SERVICE')return renderSelfService();}
  function patchModuleManager(root=document){
    root.querySelectorAll('[data-module-open]').forEach(button=>{const id=button.dataset.moduleOpen;if(!FINAL_MODULES.has(id))return;if(button.dataset.e48Bound)return;button.dataset.e48Bound='1';button.disabled=false;const span=button.querySelector('span');if(span)span.textContent='Abrir módulo';button.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();renderFinalModule(id);},true);});
    const enabled=root.querySelector('.vertical-enabled');if(enabled&&!enabled.querySelector('#e53-access-card')){const box=document.createElement('div');box.className='vertical-card-grid';box.innerHTML='<button id="e53-access-card" type="button" class="vertical-card"><strong>Acesso mobile / QR</strong><span>HTTP local em LAN confiável</span></button><button id="e54-hardware-card" type="button" class="vertical-card"><strong>Periféricos</strong><span>Diagnóstico e homologação</span></button>';enabled.appendChild(box);box.querySelector('#e53-access-card').addEventListener('click',renderMobileAccess);box.querySelector('#e54-hardware-card').addEventListener('click',renderHardware);}
  }
  const observer=new MutationObserver(()=>patchModuleManager(document));observer.observe(document.body,{subtree:true,childList:true});patchModuleManager(document);

  async function maybeOnboarding(){
    try{const state=await req('/api/v1/vertical/onboarding');if(state.completed)return;const modules=await api.modules();const root=content();if(!root)return;root.innerHTML=`<section class="page vertical-page"><header class="page-head"><div><h1>Configuração inicial</h1><p>Escolha o segmento; a recomendação pode ser alterada antes de concluir.</p></div><span class="vertical-rule">Local-first · pagamentos manuais · somente NÃO FISCAL</span></header><div class="data-card"><form id="onboarding-form" class="vertical-form">${field('businessName','Nome do estabelecimento')}<label class="field"><span>Segmento</span><select name="segment">${['GENERIC','RESTAURANT','PIZZERIA','FAST_FOOD','MARKET','BAKERY','RETAIL','SERVICES','WORKSHOP'].map(segment=>`<option value="${segment}">${segment}</option>`).join('')}</select></label><div id="onboarding-modules">${modules.map(module=>`<label class="vertical-toggle"><span><strong>${esc(module.name)}</strong><small>${esc(module.description||'')}</small></span><input type="checkbox" name="moduleIds" value="${module.id}"></label>`).join('')}</div><button class="primary-button" type="submit">Concluir configuração</button></form></div></section>`;
      const form=document.getElementById('onboarding-form');async function recommend(){const segment=new FormData(form).get('segment');const result=await req(`/api/v1/vertical/onboarding/recommend?segment=${e(segment)}`);form.querySelectorAll('[name="moduleIds"]').forEach(input=>input.checked=result.moduleIds.includes(input.value));}form.querySelector('[name="segment"]').addEventListener('change',()=>recommend().catch(error=>notify(error.message,true)));form.addEventListener('submit',async event=>{event.preventDefault();const data=new FormData(form);try{await req('/api/v1/vertical/onboarding/complete',{method:'POST',body:{businessName:data.get('businessName'),segment:data.get('segment'),moduleIds:data.getAll('moduleIds')}});notify('Configuração inicial concluída.');document.querySelector('[data-route="home"]')?.click();}catch(error){notify(error.message,true);}});await recommend();
    }catch{/* app pode ainda estar inicializando */}
  }
  setTimeout(maybeOnboarding,900);
})();