'use strict';

(() => {
  const root=window;const {ApiClient}=root.PdvApiClient;const api=new ApiClient();const content=document.getElementById('route-content');let rendering=false;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]);
  const when=value=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
  const money=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const badge=value=>`<span class="ops-badge status-${esc(String(value||'').toLowerCase())}">${esc(value||'—')}</span>`;
  const toast=(message,type='')=>{const host=document.getElementById('toast-root');if(!host)return;const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;host.appendChild(el);setTimeout(()=>el.remove(),3500);};
  const request=(path,options)=>api.request(path,options);

  function actions(doc){const buttons=[`<button class="ops-link" data-fiscal-detail="${esc(doc.id)}">Detalhes</button>`];const contingency=doc.contingency||null;
    if(doc.lifecycleStatus==='UNKNOWN')buttons.push(`<button class="ops-link" data-fiscal-reconcile="${esc(doc.id)}">Reconciliar</button>`);
    if(doc.lifecycleStatus==='FAILED'||(doc.lifecycleStatus==='UNKNOWN'&&!doc.reconcileRequired&&doc.lastReconcileStatus==='NOT_FOUND'))buttons.push(`<button class="ops-link" data-fiscal-retry="${esc(doc.id)}">Tentar novamente</button>`);
    if(['AUTHORIZED','CANCELLED'].includes(doc.lifecycleStatus)){buttons.push(`<button class="ops-link" data-fiscal-xml="${esc(doc.id)}" data-kind="authorized">XML</button>`);buttons.push(`<button class="ops-link" data-fiscal-danfe="${esc(doc.id)}">DANFE</button>`);}
    if(doc.lifecycleStatus==='AUTHORIZED')buttons.push(`<button class="ops-link danger" data-fiscal-cancel="${esc(doc.id)}">Cancelar</button>`);
    if(doc.lifecycleStatus==='CANCELLED')buttons.push(`<button class="ops-link" data-fiscal-xml="${esc(doc.id)}" data-kind="cancellation">XML cancelamento</button>`);
    if(!contingency&&doc.lifecycleStatus==='PENDING'&&Number(doc.attemptCount||0)===0)buttons.push(`<button class="ops-link" data-fiscal-contingency-enter="${esc(doc.id)}">Entrar em contingência</button>`);
    if(contingency&&contingency.status==='ISSUED'&&!contingency.hasGeneratedXml)buttons.push(`<button class="ops-link" data-fiscal-contingency-prepare="${esc(doc.id)}">Gerar XML offline</button>`);
    if(contingency&&contingency.status==='ISSUED'&&contingency.hasGeneratedXml)buttons.push(`<button class="ops-link" data-fiscal-contingency-send="${esc(doc.id)}">Transmitir contingência</button>`);
    if(contingency&&contingency.status==='RECONCILING')buttons.push(`<button class="ops-link" data-fiscal-contingency-reconcile="${esc(doc.id)}">Reconciliar contingência</button>`);
    return `<div class="ops-row-actions">${buttons.join('')}</div>`;
  }

  async function load(status=''){await api.initialize();const docs=await api.fiscalDocuments(status?{status}:{});let contingencies=[];try{contingencies=await request('/api/v1/fiscal/contingencies');}catch{}const byId=new Map((Array.isArray(contingencies)?contingencies:[]).map(item=>[String(item.fiscalDocumentId),item]));return docs.map(doc=>({...doc,contingency:byId.get(String(doc.id))||null}));}
  async function loadProduction(){await api.initialize();return request('/api/v1/fiscal/production/readiness');}
  async function desktopStatus(){const fiscal=root.artisysDesktop?.fiscal;if(!fiscal)return{certificate:{configured:false},connection:{configured:false}};const [certificate,connection]=await Promise.all([fiscal.certificateStatus?.().catch(()=>({configured:false})),fiscal.status?.().catch(()=>({configured:false}))]);return{certificate:certificate||{configured:false},connection:connection||{configured:false}};}

  function readinessRows(readiness){return (readiness?.checks||[]).map(item=>`<tr><td>${item.passed?'✓':'—'}</td><td><strong>${esc(item.label)}</strong><small>${esc(item.message||'')}</small></td><td>${badge(item.passed?'OK':'PENDENTE')}</td></tr>`).join('')||'<tr><td colspan="3">Checklist indisponível.</td></tr>';}
  function productionHtml(readiness,desktop){const settings=readiness?.settings||{};const certificate=desktop?.certificate||{};const connection=desktop?.connection||{};return `
    <div class="ops-card-head"><div><h2>Fiscal · Configuração e Produção</h2><p class="ops-muted">Produção só é liberada após checklist bloqueante. O núcleo local usa ACBr; provedores pagos permanecem opcionais.</p></div><div class="ops-row-actions"><button id="fiscal-production-refresh" class="ops-secondary">Atualizar</button></div></div>
    <dl class="ops-details"><div><dt>Provedor</dt><dd>${esc(settings.provider||connection.provider||'—')}</dd></div><div><dt>Ambiente</dt><dd>${badge(settings.environment||connection.environment||'—')}</dd></div><div><dt>Série</dt><dd>${esc(settings.series||'—')}</dd></div><div><dt>Emitente</dt><dd>${esc(settings.legalName||settings.cnpj||'—')}</dd></div><div><dt>Certificado A1</dt><dd>${certificate.configured?(certificate.expired?'Vencido':`Configurado · vence ${when(certificate.certificate?.validTo)}`):'Não configurado'}</dd></div><div><dt>Status SEFAZ</dt><dd id="fiscal-sefaz-status">Não testado nesta sessão</dd></div></dl>
    <div class="ops-row-actions" style="margin:12px 0"><button id="fiscal-use-acbr" class="ops-secondary">Usar ACBr local</button><button id="fiscal-import-a1" class="ops-secondary">Importar certificado A1</button><button id="fiscal-test-sidecar" class="ops-secondary">Testar sidecar</button><button id="fiscal-test-sefaz" class="ops-secondary">Testar SEFAZ</button></div>
    <div class="ops-card-head"><div><h3>Checklist de produção</h3><p class="ops-muted">CNPJ/IE/CRT, perfis tributários, sequência, certificado, CSC NFC-e, homologação, cancelamento, DANFE e backup precisam estar validados.</p></div>${readiness?.ready?badge('PRONTO'):badge('BLOQUEADO')}</div>
    <div class="ops-table-wrap"><table class="ops-table"><thead><tr><th></th><th>Verificação</th><th>Estado</th></tr></thead><tbody>${readinessRows(readiness)}</tbody></table></div>
    <div class="ops-row-actions" style="margin-top:12px">${readiness?.enabled?'<button id="fiscal-production-disable" class="ops-secondary">Voltar para homologação</button>':`<button id="fiscal-production-enable" class="ops-primary" ${readiness?.ready?'':'disabled'}>Ativar produção</button>`}</div>`;}

  function stillOnSettings(page){const currentPage=content?.querySelector('.ops-page');const heading=content?.querySelector('.ops-head h1');return Boolean(page?.isConnected&&currentPage===page&&heading?.textContent?.trim()==='Configurações');}
  function retryMount(){setTimeout(()=>{if(content?.querySelector('.ops-head h1')?.textContent?.trim()==='Configurações'&&!content.querySelector('#fiscal-monitor-panel'))void mount();},250);}
  async function mount(){
    if(rendering||!content||content.querySelector('#fiscal-monitor-panel'))return;
    const page=content.querySelector('.ops-page');const heading=content.querySelector('.ops-head h1');if(!page||!heading||heading.textContent.trim()!=='Configurações')return;
    rendering=true;
    try{
      const [docs,readiness,desktop]=await Promise.all([load(),loadProduction(),desktopStatus()]);
      if(!stillOnSettings(page)||content.querySelector('#fiscal-monitor-panel')){if(content.querySelector('.ops-head h1')?.textContent?.trim()==='Configurações')retryMount();return;}
      const production=document.createElement('section');production.id='fiscal-production-panel';production.className='ops-card';production.innerHTML=productionHtml(readiness,desktop);page.appendChild(production);wireProduction(production);
      const panel=document.createElement('section');panel.id='fiscal-monitor-panel';panel.className='ops-card';panel.innerHTML=`
        <div class="ops-card-head"><div><h2>Fiscal · Documentos</h2><p class="ops-muted">Monitor local de NFC-e/NF-e. Estados incertos exigem reconciliação antes de reenvio; contingência não apaga o estado fiscal original.</p></div><div class="ops-row-actions"><select id="fiscal-status-filter" class="ops-input compact"><option value="">Todos</option>${['PENDING','PROCESSING','AUTHORIZED','REJECTED','UNKNOWN','FAILED','CANCELLED'].map(s=>`<option>${s}</option>`).join('')}</select><button id="fiscal-refresh" class="ops-secondary">Atualizar</button></div></div>
        <div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Venda</th><th>Documento</th><th>Estado</th><th>Chave</th><th>Tentativas</th><th>Atualização</th><th>Ações</th></tr></thead><tbody id="fiscal-monitor-body">${rows(docs)}</tbody></table></div>
        <div id="fiscal-monitor-detail"></div>`;
      page.appendChild(panel);wire(panel);
    }catch(error){console.warn('Fiscal monitor unavailable:',error?.message||error);retryMount();}finally{rendering=false;}
  }
  function rows(docs){return docs.map(doc=>`<tr><td>${esc(doc.saleId)}</td><td><strong>${esc((doc.documentType||'').toUpperCase())}</strong><small>${esc(doc.number||'—')} · série ${esc(doc.series||'—')}</small></td><td>${badge(doc.lifecycleStatus)}${doc.contingency?`<small>Contingência: ${esc(doc.contingency.status)}</small>`:''}</td><td>${esc(doc.accessKey?`${doc.accessKey.slice(0,8)}…${doc.accessKey.slice(-6)}`:(doc.contingency?.accessKey?`${doc.contingency.accessKey.slice(0,8)}…${doc.contingency.accessKey.slice(-6)}`:'—'))}</td><td>${esc(doc.attemptCount)}</td><td>${when(doc.updatedAt)}</td><td>${actions(doc)}</td></tr>`).join('')||'<tr><td colspan="7">Nenhum documento fiscal registrado.</td></tr>';}
  async function refresh(panel){const status=panel.querySelector('#fiscal-status-filter')?.value||'';panel.querySelector('#fiscal-monitor-body').innerHTML=rows(await load(status));wireRows(panel);}
  async function detail(panel,id){const result=await request(`/api/v1/fiscal/documents/${encodeURIComponent(id)}/monitor`);const doc=result.document;let contingency=null;try{contingency=await request(`/api/v1/fiscal/documents/${encodeURIComponent(id)}/contingency`);}catch{}panel.querySelector('#fiscal-monitor-detail').innerHTML=`<section class="ops-card"><div class="ops-card-head"><h3>${esc(doc.reference)}</h3>${badge(doc.lifecycleStatus)}</div><dl class="ops-details"><div><dt>Venda</dt><dd>${esc(result.sale?.saleNumber||doc.saleId)}</dd></div><div><dt>Total</dt><dd>${money(result.sale?.totalCents)}</dd></div><div><dt>Chave</dt><dd>${esc(doc.accessKey||contingency?.accessKey||'—')}</dd></div><div><dt>Protocolo</dt><dd>${esc(doc.authorizationProtocol||'—')}</dd></div><div><dt>SEFAZ</dt><dd>${esc(`${doc.sefazCode||'—'} ${doc.sefazMessage||''}`)}</dd></div><div><dt>Reconciliação</dt><dd>${esc(doc.reconcileRequired?'Obrigatória':doc.lastReconcileStatus||'—')}</dd></div>${contingency?`<div><dt>Contingência</dt><dd>${esc(`${contingency.status} · ${contingency.reason}`)}</dd></div>`:''}</dl><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Data</th><th>Evento</th><th>Estado</th><th>Retorno</th></tr></thead><tbody>${result.events.map(event=>`<tr><td>${when(event.createdAt)}</td><td>${esc(event.eventType)}</td><td>${badge(event.status)}</td><td>${esc(`${event.sefazCode||''} ${event.sefazMessage||''}`||'—')}</td></tr>`).join('')}</tbody></table></div></section>`;}

  async function refreshProduction(panel){const [readiness,desktop]=await Promise.all([loadProduction(),desktopStatus()]);panel.innerHTML=productionHtml(readiness,desktop);wireProduction(panel);}
  async function evidence(key,passed,message,metadata={}){return request('/api/v1/fiscal/production/evidence',{method:'POST',body:{key,passed,message,metadata}});}
  function wireProduction(panel){
    panel.querySelector('#fiscal-production-refresh')?.addEventListener('click',()=>refreshProduction(panel).catch(error=>toast(error.message,'error')));
    panel.querySelector('#fiscal-use-acbr')?.addEventListener('click',async()=>{try{await root.artisysDesktop?.fiscal?.save?.({provider:'acbr-local',environment:'homologation',documentType:'nfce'});toast('ACBr local configurado em homologação.','success');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelector('#fiscal-import-a1')?.addEventListener('click',async()=>{const phrase=prompt('Senha do certificado A1 (deixe vazio se não houver):','');if(phrase===null)return;const cscValue=prompt('Informe o CSC NFC-e:','');if(cscValue===null||!cscValue.trim())return;const cscId=prompt('Informe o ID do CSC NFC-e:','');if(cscId===null||!cscId.trim())return;try{const status=await root.artisysDesktop?.fiscal?.importCertificate?.({pfxPhrase:phrase,cscValue,cscId});if(status?.cancelled)return;await evidence('csc',true,'CSC armazenado no cofre seguro do processo principal.');if(status?.configured&&status?.expiryVerified&&!status?.expired)await evidence('certificate',true,'Certificado A1 importado e validade verificada.');toast('Certificado A1 e CSC configurados.','success');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelector('#fiscal-test-sidecar')?.addEventListener('click',async()=>{try{const result=await root.artisysDesktop?.fiscal?.test?.();const ok=Boolean(result?.reachable);await evidence('sidecar',ok,ok?'Sidecar fiscal respondeu ao teste local.':result?.error||'Sidecar indisponível.');toast(ok?'Sidecar fiscal acessível.':'Falha no sidecar.',ok?'success':'error');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelector('#fiscal-test-sefaz')?.addEventListener('click',async()=>{try{const result=await root.artisysDesktop?.fiscal?.sefazStatus?.();const ok=Boolean(result?.ok);await evidence('sefaz',ok,ok?'SEFAZ respondeu ao teste do provider.':result?.error||'SEFAZ indisponível.');const statusHost=panel.querySelector('#fiscal-sefaz-status');if(statusHost)statusHost.textContent=ok?'Serviço respondeu':'Falha no teste';toast(ok?'Comunicação SEFAZ validada.':'Falha ao consultar SEFAZ.',ok?'success':'error');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelector('#fiscal-production-enable')?.addEventListener('click',async()=>{if(!confirm('Ativar o ambiente fiscal de PRODUÇÃO? Emissão automática continuará desligada até configuração explícita.'))return;try{await request('/api/v1/fiscal/production/activate',{method:'POST',body:{}});try{await root.artisysDesktop?.fiscal?.setEnvironment?.('production');}catch(error){await request('/api/v1/fiscal/production/deactivate',{method:'POST',body:{}}).catch(()=>{});throw error;}toast('Produção fiscal ativada com checklist registrado.','success');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelector('#fiscal-production-disable')?.addEventListener('click',async()=>{if(!confirm('Voltar o fiscal para homologação?'))return;try{await request('/api/v1/fiscal/production/deactivate',{method:'POST',body:{}});await root.artisysDesktop?.fiscal?.setEnvironment?.('homologation').catch(()=>{});toast('Fiscal voltou para homologação.','success');await refreshProduction(panel);}catch(error){toast(error.message,'error');}});
  }

  function wireRows(panel){
    panel.querySelectorAll('[data-fiscal-detail]').forEach(button=>button.onclick=()=>detail(panel,button.dataset.fiscalDetail).catch(error=>toast(error.message,'error')));
    panel.querySelectorAll('[data-fiscal-reconcile]').forEach(button=>button.onclick=async()=>{try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalReconcile)}/reconcile`,{method:'POST',body:{},mutationId:api.mutationId()});toast('Reconciliação executada.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-retry]').forEach(button=>button.onclick=async()=>{try{await api.retryFiscalIssue(button.dataset.fiscalRetry);toast('Retry fiscal solicitado.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-cancel]').forEach(button=>button.onclick=async()=>{const reason=prompt('Justificativa do cancelamento (mínimo 15 caracteres):','');if(!reason)return;try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalCancel)}/cancel`,{method:'POST',body:{reason},mutationId:api.mutationId()});toast('Cancelamento processado.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-danfe]').forEach(button=>button.onclick=async()=>{try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalDanfe)}/danfe`,{method:'POST',body:{width:42},mutationId:api.mutationId()});toast('DANFE enviado para a fila de impressão.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-xml]').forEach(button=>button.onclick=async()=>{try{const result=await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalXml)}/xml?kind=${encodeURIComponent(button.dataset.kind||'authorized')}`);const host=panel.querySelector('#fiscal-monitor-detail');host.innerHTML=`<section class="ops-card"><div class="ops-card-head"><h3>XML fiscal · ${esc(result.kind)}</h3><button class="ops-secondary" id="fiscal-close-xml">Fechar</button></div><pre style="white-space:pre-wrap;max-height:320px;overflow:auto">${esc(result.xml)}</pre></section>`;host.querySelector('#fiscal-close-xml').onclick=()=>{host.innerHTML='';};}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-contingency-enter]').forEach(button=>button.onclick=async()=>{const reason=prompt('Motivo da contingência offline (mínimo 15 caracteres):','Indisponibilidade temporária da autorização SEFAZ');if(!reason)return;try{const result=await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalContingencyEnter)}/contingency`,{method:'POST',body:{reason}});toast(result?.warning||'Contingência registrada e XML offline preparado.',result?.warning?'':'success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-contingency-prepare]').forEach(button=>button.onclick=async()=>{try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalContingencyPrepare)}/contingency/prepare`,{method:'POST',body:{}});toast('XML offline assinado e DANFE de contingência enfileirado.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-contingency-send]').forEach(button=>button.onclick=async()=>{if(!confirm('Transmitir agora a mesma NFC-e emitida em contingência?'))return;try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalContingencySend)}/contingency/transmit`,{method:'POST',body:{}});toast('Transmissão de contingência processada.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
    panel.querySelectorAll('[data-fiscal-contingency-reconcile]').forEach(button=>button.onclick=async()=>{try{await request(`/api/v1/fiscal/documents/${encodeURIComponent(button.dataset.fiscalContingencyReconcile)}/contingency/reconcile`,{method:'POST',body:{}});toast('Reconciliação da contingência solicitada.','success');await refresh(panel);}catch(error){toast(error.message,'error');}});
  }
  function wire(panel){panel.querySelector('#fiscal-refresh')?.addEventListener('click',()=>refresh(panel).catch(error=>toast(error.message,'error')));panel.querySelector('#fiscal-status-filter')?.addEventListener('change',()=>refresh(panel).catch(error=>toast(error.message,'error')));wireRows(panel);}

  const observer=new MutationObserver(()=>{if(!content||content.querySelector('#fiscal-monitor-panel'))return;void mount();});observer.observe(content,{childList:true,subtree:false});void mount();
})();