'use strict';
(()=>{
 const root=window;const content=document.getElementById('route-content');let mounted=null;let rendering=false;
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
 const toast=(m,t='')=>{const h=document.getElementById('toast-root');if(!h)return;const e=document.createElement('div');e.className='toast '+t;e.textContent=m;h.appendChild(e);setTimeout(()=>e.remove(),3500);};
 const badge=v=>'<span class="ops-badge status-'+esc(String(v||'').toLowerCase())+'">'+esc(v||'—')+'</span>';
 const when=v=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
 function actions(d){const a=['<button class="ops-link" data-nfse-detail="'+esc(d.id)+'">Consultar</button>'];if(d.status==='PENDING')a.push('<button class="ops-link" data-nfse-process="'+esc(d.id)+'">Processar</button>');if(d.status==='UNKNOWN')a.push('<button class="ops-link" data-nfse-reconcile="'+esc(d.id)+'">Reconciliar</button>');if(d.status==='FAILED')a.push('<button class="ops-link" data-nfse-retry="'+esc(d.id)+'">Retry seguro</button>');if(d.status==='AUTHORIZED')a.push('<button class="ops-link" data-nfse-event="'+esc(d.id)+'">Registrar evento</button>');return '<div class="ops-row-actions">'+a.join('')+'</div>';}
 function rows(docs){return (docs||[]).map(d=>'<tr><td><strong>'+esc(d.reference)+'</strong><small>'+esc(d.provider)+' · '+esc(d.environment)+'</small></td><td>'+badge(d.status)+'</td><td>'+esc(d.accessKey||d.dpsId||'—')+'</td><td>'+esc(d.attempts)+'</td><td>'+when(d.updatedAt)+'</td><td>'+actions(d)+'</td></tr>').join('')||'<tr><td colspan="6">Nenhuma NFS-e registrada.</td></tr>';}
 async function detail(panel,id,api){const [doc,events]=await Promise.all([api.document(id),api.events(id)]);panel.querySelector('#nfse-detail').innerHTML='<section class="ops-card"><div class="ops-card-head"><h3>'+esc(doc.reference)+'</h3>'+badge(doc.status)+'</div><dl class="ops-details"><div><dt>Chave</dt><dd>'+esc(doc.accessKey||'—')+'</dd></div><div><dt>DPS</dt><dd>'+esc(doc.dpsId||'—')+'</dd></div><div><dt>Reconciliação</dt><dd>'+esc(doc.reconcileRequired?'Obrigatória':'Não pendente')+'</dd></div><div><dt>Erro</dt><dd>'+esc(doc.error||'—')+'</dd></div></dl><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Data</th><th>Evento</th><th>Estado</th></tr></thead><tbody>'+(events||[]).map(e=>'<tr><td>'+when(e.createdAt)+'</td><td>'+esc(e.eventType)+'</td><td>'+badge(e.status)+'</td></tr>').join('')+'</tbody></table></div></section>';}
 async function refresh(panel,api){const status=panel.querySelector('#nfse-status')?.value||'';panel.querySelector('#nfse-body').innerHTML=rows(await api.documents(status));wireRows(panel,api);}
 function wireRows(panel,api){
  panel.querySelectorAll('[data-nfse-detail]').forEach(b=>b.onclick=()=>detail(panel,b.dataset.nfseDetail,api).catch(e=>toast(e.message,'error')));
  panel.querySelectorAll('[data-nfse-process]').forEach(b=>b.onclick=async()=>{try{await api.process(b.dataset.nfseProcess);toast('Processamento NFS-e executado.','success');await refresh(panel,api);}catch(e){toast(e.message,'error');}});
  panel.querySelectorAll('[data-nfse-reconcile]').forEach(b=>b.onclick=async()=>{try{await api.reconcile(b.dataset.nfseReconcile);toast('Reconciliação NFS-e executada.','success');await refresh(panel,api);}catch(e){toast(e.message,'error');}});
  panel.querySelectorAll('[data-nfse-retry]').forEach(b=>b.onclick=async()=>{try{await api.retry(b.dataset.nfseRetry);toast('Retry NFS-e preparado sem criar novo documento.','success');await refresh(panel,api);}catch(e){toast(e.message,'error');}});
  panel.querySelectorAll('[data-nfse-event]').forEach(b=>b.onclick=async()=>{const eventType=prompt('Tipo do evento NFS-e:','CANCEL');if(!eventType)return;const signedEventXml=prompt('XML assinado do evento:','');if(!signedEventXml)return;try{await api.registerEvent(b.dataset.nfseEvent,{eventType,signedEventXml});toast('Evento NFS-e registrado.','success');await refresh(panel,api);}catch(e){toast(e.message,'error');}});
 }
 async function mount(){
  if(rendering||!content)return;const page=content.querySelector('.ops-page');const head=content.querySelector('.ops-head h1');if(!page||!head||head.textContent.trim()!=='Configurações')return;if(page===mounted&&page.querySelector('#nfse-workspace'))return;rendering=true;
  try{const api=new root.NfseApi.NfseClient();await api.initialize();const docs=await api.documents();if(!content.contains(page)||page.querySelector('#nfse-workspace'))return;const panel=document.createElement('section');panel.id='nfse-workspace';panel.className='ops-card';panel.innerHTML='<div class="ops-card-head"><div><h2>Fiscal · NFS-e</h2><p class="ops-muted">Operação de serviços separada de NFC-e/NF-e. UNKNOWN exige reconciliação antes de retry.</p></div><div class="ops-row-actions"><select id="nfse-status" class="ops-input compact"><option value="">Todos</option>'+['PENDING','PROCESSING','AUTHORIZED','REJECTED','UNKNOWN','FAILED','CANCELLED'].map(s=>'<option>'+s+'</option>').join('')+'</select><button id="nfse-refresh" class="ops-secondary">Atualizar</button></div></div><form id="nfse-issue-form" class="ops-form"><h3>Emitir NFS-e</h3><label>Referência<input name="reference" required placeholder="SERV-0001"></label><label>Ambiente<select name="environment"><option value="homologation">Homologação</option><option value="production">Produção</option></select></label><label>Payload JSON<textarea name="payload" rows="4">{}</textarea></label><label>DPS assinada<textarea name="signedDpsXml" rows="5" required placeholder="<DPS>...<Signature>...</Signature></DPS>"></textarea></label><button class="ops-primary" type="submit">Registrar emissão</button></form><div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>Referência</th><th>Estado</th><th>Identificador</th><th>Tentativas</th><th>Atualização</th><th>Ações</th></tr></thead><tbody id="nfse-body">'+rows(docs)+'</tbody></table></div><div id="nfse-detail"></div>';page.appendChild(panel);mounted=page;
   panel.querySelector('#nfse-refresh').onclick=()=>refresh(panel,api).catch(e=>toast(e.message,'error'));panel.querySelector('#nfse-status').onchange=()=>refresh(panel,api).catch(e=>toast(e.message,'error'));
   panel.querySelector('#nfse-issue-form').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.currentTarget);let payload={};try{payload=JSON.parse(String(f.get('payload')||'{}'));}catch{return toast('Payload JSON inválido.','error');}try{const doc=await api.requestIssue({reference:f.get('reference'),environment:f.get('environment'),payload,signedDpsXml:f.get('signedDpsXml')});toast('NFS-e registrada para processamento.','success');await refresh(panel,api);await detail(panel,doc.id,api);}catch(e){toast(e.message,'error');}};
   wireRows(panel,api);
  }catch(e){console.warn('NFS-e workspace unavailable:',e?.message||e);}finally{rendering=false;}
 }
 if(content){new MutationObserver(()=>queueMicrotask(mount)).observe(content,{childList:true,subtree:false});queueMicrotask(mount);}
})();