'use strict';
(() => {
  const ApiClient=window.PdvApiClient?.ApiClient;if(!ApiClient)return;
  const api=new ApiClient();
  const ROUTES=new Set(['home','checkout','products','customers','inventory','finance','reports','sellers','cash','sales','returns','settings']);
  let lastRoute='';let queued=false;
  function sessionReady(){return Boolean(window.sessionStorage?.getItem('artisys.sessionToken'));}
  async function send(eventName,payload={}){if(!sessionReady())return;try{await api.request('/api/v1/system/telemetry/events',{method:'POST',body:{eventName,payload}});}catch{/* telemetry nunca gera toast/erro operacional */}}
  function currentRoute(){const route=String(document.body?.dataset?.activeRoute||'');return ROUTES.has(route)?route:'';}
  function observeRoute(){const route=currentRoute();if(!route||route===lastRoute)return;lastRoute=route;void send('screen_opened',{dimensions:{route}});if(route==='returns')void send('return_started',{dimensions:{module:'returns'}});if(route==='settings')queueSettings();}
  function setting(rows,key,defaultValue=null){const row=(rows||[]).find(item=>item.key===key);return row?row.value:defaultValue;}
  function boolSetting(rows,key){return Boolean(setting(rows,key,false));}
  async function injectSettings(){queued=false;if(currentRoute()!=='settings')return;const content=document.getElementById('route-content');const host=content?.querySelector('.ops-page');if(!host||host.querySelector('#telemetry-settings-card'))return;const card=document.createElement('section');card.id='telemetry-settings-card';card.className='ops-card';card.innerHTML='<h2>Privacidade e diagnóstico</h2><div class="ops-loader">Carregando preferências…</div>';host.appendChild(card);
    try{const [rows,session]=await Promise.all([api.settings({scope:'global',prefix:'telemetry.'}),api.currentSession()]);if(!card.isConnected)return;const accepted=Number(setting(rows,'telemetry.consent_version',0)||0)>=1&&Boolean(setting(rows,'telemetry.consent_accepted_at',''));const canManage=['admin','manager'].includes(String(session?.user?.role||''));const canEdit=canManage&&accepted;const enabled=accepted&&boolSetting(rows,'telemetry.enabled');const diagnostics=accepted&&boolSetting(rows,'telemetry.diagnostics');const consentMessage=accepted?'Autorização registrada na atualização. Você pode desligar ou religar estes envios a qualquer momento.':'Nenhum envio está autorizado. A autorização inicial é apresentada na conclusão da atualização, não nesta tela.';card.innerHTML=`<div class="ops-card-head"><div><h2>Privacidade e diagnóstico</h2><p>Ajude a ArtiSys a mapear fluxos e falhas técnicas. A coleta é opcional e o PDV continua funcionando sem internet ou Cloudflare.</p></div><span class="ops-badge ${enabled?'status-ok':''}">${enabled?'ATIVA':'DESATIVADA'}</span></div><form id="telemetry-settings-form" class="ops-form"><label class="printing-check"><input name="enabled" type="checkbox" ${enabled?'checked':''}> Enviar métricas anônimas de uso e fluxo</label><label class="printing-check"><input name="diagnostics" type="checkbox" ${diagnostics?'checked':''}> Enviar fingerprints e categorias técnicas de falhas</label><p class="ops-muted">${consentMessage}</p><p class="ops-muted">Nunca são enviados nome, CPF/CNPJ, e-mail, telefone, endereço, senha, token, XML/DANFE, dados de cartão, observações, conteúdo de recibos ou texto digitado.</p><div class="ops-actions"><button type="submit" class="ops-primary">Salvar privacidade</button><span id="telemetry-settings-status" class="ops-muted" aria-live="polite"></span></div></form>${canManage?'':'<p class="ops-muted">Somente gerente ou administrador pode alterar estas opções.</p>'}`;const form=card.querySelector('#telemetry-settings-form');if(!canEdit){form.querySelectorAll('input,button').forEach(node=>{node.disabled=true;});return;}form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');const status=card.querySelector('#telemetry-settings-status');button.disabled=true;status.textContent='Salvando…';try{const nextEnabled=Boolean(form.elements.namedItem('enabled')?.checked);const nextDiagnostics=Boolean(form.elements.namedItem('diagnostics')?.checked);await api.saveSetting('telemetry.enabled',nextEnabled);await api.saveSetting('telemetry.diagnostics',nextDiagnostics);status.textContent='Preferências salvas.';const badge=card.querySelector('.ops-badge');badge.textContent=nextEnabled?'ATIVA':'DESATIVADA';badge.classList.toggle('status-ok',nextEnabled);}catch(error){status.textContent=error?.message||'Falha ao salvar preferências.';}finally{button.disabled=false;}});
    }catch(error){card.innerHTML=`<h2>Privacidade e diagnóstico</h2><p class="ops-error">${String(error?.message||'Não foi possível carregar as preferências.')}</p>`;}
  }
  function queueSettings(){if(queued)return;queued=true;setTimeout(()=>{void injectSettings();},0);}
  const observer=new MutationObserver(()=>{observeRoute();if(currentRoute()==='settings')queueSettings();});observer.observe(document.body,{attributes:true,attributeFilter:['data-active-route']});const content=document.getElementById('route-content');if(content)observer.observe(content,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',observeRoute,{once:true});observeRoute();
  window.PdvTelemetryUi=Object.freeze({send,observeRoute,injectSettings});
})();
