'use strict';
const { randomUUID } = require('node:crypto');
const { withTransaction } = require('../../core/database/sqlite-database');
const { writeAudit } = require('../../core/audit-log');
const { roundQuantity } = require('../inventory/inventory-rules');
const { assertCents } = require('../shared/money');

function createProcurementService({db,inventory,finance,now=()=>new Date().toISOString(),idFactory=p=>`${p}-${randomUUID()}`}={}){
  if(!db||!inventory||!finance)throw new TypeError('db, inventory and finance are required.');
  const requireManager=actor=>{if(!['manager','admin'].includes(String(actor?.role||'')))throw new Error('Autorizacao de gerente necessaria para compras.');};
  const text=v=>String(v||'').trim();
  const location=v=>text(v)||'MAIN';
  const qty=v=>roundQuantity(Number(v));

  function mapItem(row){return row&&{id:row.id,purchaseOrderId:row.purchase_order_id,productId:row.product_id,productName:row.product_name,sku:row.sku,quantity:qty(row.quantity),receivedQuantity:qty(row.received_quantity),pendingQuantity:qty(row.quantity-row.received_quantity),unitCostCents:row.unit_cost_cents,totalCents:row.total_cents,createdAt:row.created_at,updatedAt:row.updated_at};}
  function mapReceipt(row){if(!row)return null;return{id:row.id,receiptNumber:row.receipt_number,purchaseOrderId:row.purchase_order_id,status:row.status,stockLocationId:row.stock_location_id,receivedById:row.received_by_id,totalCents:row.total_cents,payableEntryId:row.payable_entry_id,mutationKey:row.mutation_key,receivedAt:row.received_at,createdAt:row.created_at,updatedAt:row.updated_at,items:db.prepare('SELECT * FROM purchase_receipt_items WHERE purchase_receipt_id=? ORDER BY created_at,id').all(row.id).map(item=>({id:item.id,purchaseReceiptId:item.purchase_receipt_id,purchaseOrderItemId:item.purchase_order_item_id,productId:item.product_id,quantity:qty(item.quantity),unitCostCents:item.unit_cost_cents,totalCents:item.total_cents,createdAt:item.created_at}))};}
  function mapOrder(row){if(!row)return null;const supplier=db.prepare('SELECT name FROM suppliers WHERE id=?').get(row.supplier_id);const items=db.prepare('SELECT * FROM purchase_order_items WHERE purchase_order_id=? ORDER BY created_at,id').all(row.id).map(mapItem);return{id:row.id,orderNumber:row.order_number,supplierId:row.supplier_id,supplierName:supplier?.name||null,status:row.status,stockLocationId:row.stock_location_id,expectedAt:row.expected_at,notes:row.notes,createdById:row.created_by_id,createdAt:row.created_at,updatedAt:row.updated_at,receivedAt:row.received_at,totalCents:items.reduce((sum,item)=>sum+item.totalCents,0),items};}
  function getPurchaseOrder(id){return mapOrder(db.prepare('SELECT * FROM purchase_orders WHERE id=?').get(String(id)));}
  function requireOrder(id){const row=db.prepare('SELECT * FROM purchase_orders WHERE id=?').get(String(id));if(!row)throw new Error('Pedido de compra nao encontrado.');return row;}
  function getReceiptByMutation(key){const row=db.prepare('SELECT * FROM purchase_receipts WHERE mutation_key=?').get(String(key));return mapReceipt(row);}

  function createPurchaseOrder(input={},actor=null){
    requireManager(actor);
    const supplierId=text(input.supplierId);const supplier=db.prepare('SELECT id FROM suppliers WHERE id=? AND active=1').get(supplierId);if(!supplier)throw new Error('Fornecedor nao encontrado ou inativo.');
    const stockLocationId=location(input.locationId||input.stockLocationId);if(!db.prepare('SELECT id FROM stock_locations WHERE id=? AND active=1').get(stockLocationId))throw new Error('Local de estoque nao encontrado ou inativo.');
    if(!Array.isArray(input.items)||!input.items.length)throw new Error('Pedido de compra deve possuir ao menos um item.');
    const seen=new Set();
    const normalized=input.items.map(item=>{const productId=text(item.productId);if(seen.has(productId))throw new Error('Produto duplicado no pedido de compra.');seen.add(productId);const product=db.prepare('SELECT id,name,sku FROM products WHERE id=? AND active=1').get(productId);if(!product)throw new Error(`Produto ${productId} nao encontrado ou inativo.`);const quantity=qty(item.quantity);if(!Number.isFinite(quantity)||quantity<=0)throw new Error('Quantidade do pedido deve ser maior que zero.');const unitCostCents=assertCents(Number(item.unitCostCents),'unitCostCents');if(unitCostCents<0)throw new Error('Custo unitario nao pode ser negativo.');return{product,quantity,unitCostCents,totalCents:Math.round(quantity*unitCostCents)};});
    const id=text(input.id||idFactory('po'));const orderNumber=text(input.orderNumber||`PO-${id}`);const ts=now();
    return withTransaction(db,()=>{db.prepare(`INSERT INTO purchase_orders(id,order_number,supplier_id,status,stock_location_id,expected_at,notes,created_by_id,created_at,updated_at) VALUES(?,?,?,'DRAFT',?,?,?,?,?,?)`).run(id,orderNumber,supplierId,stockLocationId,input.expectedAt||null,input.notes||null,actor?.userId||null,ts,ts);const insert=db.prepare(`INSERT INTO purchase_order_items(id,purchase_order_id,product_id,product_name,sku,quantity,received_quantity,unit_cost_cents,total_cents,created_at,updated_at) VALUES(?,?,?,?,?,?,0,?,?,?,?)`);for(const item of normalized)insert.run(idFactory('poi'),id,item.product.id,item.product.name,item.product.sku,item.quantity,item.unitCostCents,item.totalCents,ts,ts);writeAudit(db,{action:'procurement.order.create',entity:'purchase-order',entityId:id,actor,context:{supplierId,stockLocationId,itemCount:normalized.length}},now);return getPurchaseOrder(id);});
  }

  function submitPurchaseOrder(id,actor=null){requireManager(actor);const order=requireOrder(id);if(order.status==='ORDERED'||order.status==='PARTIALLY_RECEIVED'||order.status==='RECEIVED')return getPurchaseOrder(id);if(order.status!=='DRAFT')throw new Error(`Pedido de compra nao pode ser enviado no status ${order.status}.`);db.prepare("UPDATE purchase_orders SET status='ORDERED',updated_at=? WHERE id=?").run(now(),String(id));writeAudit(db,{action:'procurement.order.submit',entity:'purchase-order',entityId:String(id),actor,context:{}},now);return getPurchaseOrder(id);}

  function receivePurchaseOrder(id,input={},actor=null){
    requireManager(actor);const mutationKey=text(input.idempotencyKey||input.mutationKey);if(!mutationKey)throw new Error('Chave de idempotencia obrigatoria no recebimento.');const previous=getReceiptByMutation(mutationKey);if(previous)return previous;
    return withTransaction(db,()=>{
      const order=requireOrder(id);if(!['ORDERED','PARTIALLY_RECEIVED'].includes(order.status))throw new Error(`Pedido de compra nao pode ser recebido no status ${order.status}.`);
      if(!Array.isArray(input.items)||!input.items.length)throw new Error('Recebimento deve possuir ao menos um item.');
      const orderItems=db.prepare('SELECT * FROM purchase_order_items WHERE purchase_order_id=? ORDER BY created_at,id').all(order.id);const byProduct=new Map(orderItems.map(row=>[String(row.product_id),row]));const seen=new Set();const normalized=[];let totalCents=0;
      for(const item of input.items){const productId=text(item.productId);if(seen.has(productId))throw new Error('Produto duplicado no recebimento.');seen.add(productId);const poItem=byProduct.get(productId);if(!poItem)throw new Error(`Produto ${productId} nao pertence ao pedido de compra.`);const quantity=qty(item.quantity);if(quantity<=0)throw new Error('Quantidade recebida deve ser maior que zero.');const pending=qty(poItem.quantity-poItem.received_quantity);if(quantity>pending)throw new Error(`Quantidade recebida excede a quantidade pendente (${pending}).`);const line=Math.round(quantity*Number(poItem.unit_cost_cents));normalized.push({poItem,productId,quantity,totalCents:line});totalCents+=line;}
      const receiptId=text(input.id||idFactory('receipt'));const receiptNumber=text(input.receiptNumber||`REC-${receiptId}`);const ts=now();
      db.prepare(`INSERT INTO purchase_receipts(id,receipt_number,purchase_order_id,status,stock_location_id,received_by_id,total_cents,mutation_key,received_at,created_at,updated_at) VALUES(?,?,?,'RECEIVED',?,?,?,?,?,?,?)`).run(receiptId,receiptNumber,order.id,order.stock_location_id,actor?.userId||null,totalCents,mutationKey,ts,ts,ts);
      const insertReceiptItem=db.prepare(`INSERT INTO purchase_receipt_items(id,purchase_receipt_id,purchase_order_item_id,product_id,quantity,unit_cost_cents,total_cents,created_at) VALUES(?,?,?,?,?,?,?,?)`);
      for(const item of normalized){const product=db.prepare('SELECT cost_cents FROM products WHERE id=?').get(item.productId);const aggregateBefore=inventory.getBalance(item.productId,{aggregate:true});const oldCost=Number(product?.cost_cents||0);inventory.move({productId:item.productId,locationId:order.stock_location_id,type:'purchase',quantityDelta:item.quantity,reason:`Recebimento ${receiptNumber}`,sourceType:'purchase-receipt',sourceId:receiptId},actor);const denominator=roundQuantity(aggregateBefore+item.quantity);const weighted=denominator>0?Math.round(((aggregateBefore*oldCost)+(item.quantity*Number(item.poItem.unit_cost_cents)))/denominator):Number(item.poItem.unit_cost_cents);db.prepare('UPDATE products SET cost_cents=?,updated_at=? WHERE id=?').run(weighted,ts,item.productId);db.prepare('UPDATE purchase_order_items SET received_quantity=received_quantity+?,updated_at=? WHERE id=?').run(item.quantity,ts,item.poItem.id);insertReceiptItem.run(idFactory('reci'),receiptId,item.poItem.id,item.productId,item.quantity,item.poItem.unit_cost_cents,item.totalCents,ts);}
      let payableEntryId=null;if(totalCents>0){const payable=finance.createEntry({kind:'PAYABLE',description:`Recebimento ${receiptNumber}`,category:'COMPRAS',amountCents:totalCents,dueAt:input.dueAt||order.expected_at||ts,sourceType:'purchase-receipt',sourceId:receiptId,notes:`Fornecedor ${order.supplier_id}`},actor);payableEntryId=payable.id;db.prepare('UPDATE purchase_receipts SET payable_entry_id=?,updated_at=? WHERE id=?').run(payableEntryId,ts,receiptId);}
      const pending=Number(db.prepare('SELECT COUNT(*) AS n FROM purchase_order_items WHERE purchase_order_id=? AND received_quantity < quantity').get(order.id).n||0);const status=pending?'PARTIALLY_RECEIVED':'RECEIVED';db.prepare('UPDATE purchase_orders SET status=?,received_at=?,updated_at=? WHERE id=?').run(status,status==='RECEIVED'?ts:null,ts,order.id);writeAudit(db,{action:'procurement.receipt.create',entity:'purchase-receipt',entityId:receiptId,actor,context:{purchaseOrderId:order.id,totalCents,status}},now);return mapReceipt(db.prepare('SELECT * FROM purchase_receipts WHERE id=?').get(receiptId));
    });
  }

  function listPurchaseOrders(filters={}){const clauses=[];const params=[];if(filters.status){clauses.push('status=?');params.push(String(filters.status).toUpperCase());}if(filters.supplierId){clauses.push('supplier_id=?');params.push(String(filters.supplierId));}if(filters.locationId){clauses.push('stock_location_id=?');params.push(location(filters.locationId));}return db.prepare(`SELECT * FROM purchase_orders${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY created_at DESC,id DESC`).all(...params).map(mapOrder);}
  function listReceipts({purchaseOrderId=null}={}){const rows=purchaseOrderId?db.prepare('SELECT * FROM purchase_receipts WHERE purchase_order_id=? ORDER BY received_at,id').all(String(purchaseOrderId)):db.prepare('SELECT * FROM purchase_receipts ORDER BY received_at,id').all();return rows.map(mapReceipt);}
  return{createPurchaseOrder,submitPurchaseOrder,receivePurchaseOrder,getPurchaseOrder,listPurchaseOrders,listReceipts};
}
module.exports={createProcurementService};
