'use strict';

(()=>{
  const token=decodeURIComponent(location.pathname.split('/').filter(Boolean)[1]||'');
  const state={context:null,query:'',category:'Todos',cart:[],busy:false,activeProduct:null};
  const $=selector=>document.querySelector(selector);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const money=cents=>(Number(cents||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const qty=value=>Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:3});
  const mutationId=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
  let toastTimer=null;

  function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),3200);}
  function setBanner(message=''){const node=$('#connection-banner');node.textContent=message;node.classList.toggle('hidden',!message);}
  async function request(path,{method='GET',body,mutation=false}={}){const headers={};if(body!==undefined)headers['content-type']='application/json';if(mutation)headers['x-mutation-id']=mutationId();const response=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.error||`Erro HTTP ${response.status}`);return data;}
  function apiPath(suffix=''){return `/api/v1/public/menu/${encodeURIComponent(token)}${suffix}`;}

  function productPhoto(product){return product.photo?`<img class="product-photo" src="${apiPath(`/products/${encodeURIComponent(product.id)}/photo`)}" alt="" loading="lazy">`:`<div class="photo-placeholder" aria-hidden="true">A</div>`;}
  function hasConfiguration(product){const c=product.configuration||{};return Boolean(c.variants?.length||c.groups?.length||c.combos?.length);}
  function visibleProducts(){const list=state.context?.products||[];const term=state.query.trim().toLocaleLowerCase('pt-BR');return list.filter(product=>{const matchesCategory=state.category==='Todos'||product.categoryName===state.category;const haystack=`${product.name} ${product.description||''} ${product.categoryName||''}`.toLocaleLowerCase('pt-BR');return matchesCategory&&(!term||haystack.includes(term));});}

  function renderCategories(){const nav=$('#category-nav');const categories=['Todos',...(state.context?.categories||[])];nav.innerHTML=categories.map(name=>`<button class="category-chip" type="button" data-category="${esc(name)}" aria-pressed="${name===state.category?'true':'false'}">${esc(name)}</button>`).join('');nav.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{state.category=button.dataset.category;renderCategories();renderProducts();}));}
  function renderProducts(){const host=$('#products');const products=visibleProducts();host.innerHTML=products.map(product=>`<article class="product-card"><div class="product-copy"><span class="product-category">${esc(product.categoryName||'Outros')}</span><h2>${esc(product.name)}</h2><p class="product-description">${esc(product.description||'Descrição disponível no balcão.')}</p><div class="product-bottom"><span class="product-price">${money(product.salePriceCents)}</span>${product.available?`<button class="add-button" type="button" data-product="${esc(product.id)}" aria-label="Adicionar ${esc(product.name)}">${hasConfiguration(product)?'Escolher':'Adicionar'}</button>`:'<span class="sold-out">Indisponível</span>'}</div></div>${productPhoto(product)}</article>`).join('')||'<div class="empty-state"><strong>Nenhum item encontrado.</strong><p>Limpe a busca ou escolha outra categoria.</p></div>';host.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>selectProduct(button.dataset.product)));}
  function renderOrders(){const session=state.context?.session;$('#table-total').textContent=money(session?.totalCents||0);const host=$('#table-orders');if(!session?.orders?.length){host.innerHTML='<h2 id="orders-title">Pedidos da mesa</h2><p>Nenhum pedido enviado ainda.</p>';return;}host.innerHTML=`<h2 id="orders-title">Pedidos da mesa</h2><p>Itens já registrados nesta comanda.</p><div class="order-list">${session.orders.slice().reverse().map(order=>`<div class="order-row"><div><strong>${order.items.map(item=>`${qty(item.quantity)}× ${esc(item.productName)}`).join(' · ')}</strong><small>${new Date(order.createdAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</small></div><div><span class="order-status">Enviado</span><strong>${money(order.totalCents)}</strong></div></div>`).join('')}</div>`;}
  function renderCartRail(){const count=state.cart.reduce((sum,line)=>sum+Number(line.quantity||0),0);const total=state.cart.reduce((sum,line)=>sum+line.unitPriceCents*line.quantity,0);$('#cart-count').textContent=`${qty(count)} ${count===1?'item':'itens'}`;$('#cart-total').textContent=money(total);$('#cart-rail').classList.toggle('hidden',!state.cart.length);}
  function render(){const context=state.context;if(!context)return;document.title=`${context.table.label} — Cardápio ArtiSys`;$('#table-badge').textContent=context.table.label;renderCategories();renderProducts();renderOrders();renderCartRail();}

  function calculateDraft(product,form){let cents=Number(product.salePriceCents||0);const variantId=String(new FormData(form).get('variantId')||'');const variant=(product.configuration?.variants||[]).find(item=>item.id===variantId);if(variant)cents+=Number(variant.priceDeltaCents||0);form.querySelectorAll('[data-option]:checked').forEach(input=>{cents+=Number(input.dataset.delta||0);});form.querySelectorAll('[data-combo]:checked').forEach(input=>{cents+=Number(input.dataset.delta||0);});return cents;}
  function refreshDraftPrice(){const form=$('#product-form');const product=state.activeProduct;if(!form||!product)return;form.querySelector('[data-draft-price]').textContent=money(calculateDraft(product,form));}
  function choicePrice(delta){const value=Number(delta||0);return value?`<span>${value>0?'+':''}${money(value)}</span>`:'<span>Incluso</span>';}

  function productDialogHtml(product){const config=product.configuration||{};const variantBlock=config.variants?.length?`<fieldset class="choice-group"><legend>Variação</legend><span class="choice-help">Escolha somente se este item tiver uma variação específica.</span>${config.variants.map(variant=>`<div class="choice"><label><input type="radio" name="variantId" value="${esc(variant.id)}"><span>${esc(variant.name)}</span></label>${choicePrice(variant.priceDeltaCents)}</div>`).join('')}</fieldset>`:'';const groups=(config.groups||[]).map(group=>{const type=group.selectionType==='SINGLE'?'radio':'checkbox';const name=`group-${group.id}`;const min=Math.max(Number(group.minSelections||0),group.required?1:0);return `<fieldset class="choice-group" data-group="${esc(group.id)}" data-min="${min}" data-max="${Number(group.maxSelections||1)}"><legend>${esc(group.name)}</legend><span class="choice-help">${min?`Escolha pelo menos ${min}. `:''}Máximo ${Number(group.maxSelections||1)}.</span>${group.options.map(option=>`<div class="choice"><label><input data-option data-delta="${Number(option.priceDeltaCents||0)}" type="${type}" name="${esc(name)}" value="${esc(option.id)}"><span>${esc(option.name)}</span></label>${choicePrice(option.priceDeltaCents)}</div>`).join('')}</fieldset>`;}).join('');const combos=(config.combos||[]).map(group=>`<fieldset class="choice-group" data-combo-group="${esc(group.id)}" data-min="${Number(group.minSelections||0)}" data-max="${Number(group.maxSelections||1)}"><legend>${esc(group.name)}</legend><span class="choice-help">Escolha de ${Number(group.minSelections||0)} a ${Number(group.maxSelections||1)}.</span>${group.items.map(item=>`<div class="choice"><label><input data-combo data-group-id="${esc(group.id)}" data-product-id="${esc(item.productId)}" data-delta="${Number(item.priceDeltaCents||0)}" type="checkbox"><span>${esc(item.productName)}</span></label>${choicePrice(item.priceDeltaCents)}</div>`).join('')}</fieldset>`).join('');return `<header class="sheet-head"><div><h2 id="product-dialog-title">${esc(product.name)}</h2><p>${esc(product.description||'Personalize o item antes de adicionar.')}</p></div><button class="icon-button" type="button" data-close aria-label="Fechar">×</button></header><div class="sheet-body">${variantBlock}${groups}${combos}<label class="note-field">Observação<textarea name="note" maxlength="500" placeholder="Ex.: sem cebola, molho à parte"></textarea></label><div id="product-error" class="banner hidden" role="alert"></div></div><footer class="sheet-actions"><strong data-draft-price>${money(product.salePriceCents)}</strong><button class="button primary" type="submit">Adicionar ao pedido</button></footer>`;}
  function validateConfiguration(form){for(const group of form.querySelectorAll('[data-group]')){const count=group.querySelectorAll('[data-option]:checked').length;const min=Number(group.dataset.min||0),max=Number(group.dataset.max||1);if(count<min||count>max)return `Revise ${group.querySelector('legend')?.textContent||'as opções'}: escolha entre ${min} e ${max}.`;}for(const group of form.querySelectorAll('[data-combo-group]')){const count=group.querySelectorAll('[data-combo]:checked').length;const min=Number(group.dataset.min||0),max=Number(group.dataset.max||1);if(count<min||count>max)return `Revise ${group.querySelector('legend')?.textContent||'o combo'}: escolha entre ${min} e ${max}.`;}return'';}

  function selectProduct(productId){const product=state.context?.products?.find(item=>item.id===productId);if(!product||!product.available)return;if(!hasConfiguration(product)){addLine({productId:product.id,name:product.name,quantity:1,unitPriceCents:product.salePriceCents,variantId:null,selections:[],comboSelections:[],note:''});return;}state.activeProduct=product;const dialog=$('#product-dialog'),form=$('#product-form');form.innerHTML=productDialogHtml(product);form.querySelector('[data-close]').addEventListener('click',()=>dialog.close());form.querySelectorAll('input').forEach(input=>input.addEventListener('change',refreshDraftPrice));form.addEventListener('submit',event=>{event.preventDefault();const error=validateConfiguration(form);const errorNode=$('#product-error');if(error){errorNode.textContent=error;errorNode.classList.remove('hidden');return;}errorNode.classList.add('hidden');const fd=new FormData(form);const variantId=String(fd.get('variantId')||'')||null;const selections=[...form.querySelectorAll('[data-option]:checked')].map(input=>input.value);const comboSelections=[...form.querySelectorAll('[data-combo]:checked')].map(input=>({groupId:input.dataset.groupId,productId:input.dataset.productId}));addLine({productId:product.id,name:product.name,quantity:1,unitPriceCents:calculateDraft(product,form),variantId,selections,comboSelections,note:String(fd.get('note')||'')});dialog.close();});dialog.showModal();}
  function addLine(line){state.cart.push({id:mutationId(),...line});renderCartRail();toast(`${line.name} adicionado.`);}

  function cartDialogHtml(){const total=state.cart.reduce((sum,line)=>sum+line.unitPriceCents*line.quantity,0);return `<header class="sheet-head"><div><h2 id="cart-dialog-title">Revisar pedido</h2><p>O preço final é validado pelo servidor antes do envio.</p></div><button class="icon-button" type="button" data-cart-close aria-label="Fechar">×</button></header><div class="sheet-body"><div class="cart-lines">${state.cart.map(line=>`<div class="cart-line"><div><strong>${esc(line.name)}</strong><small>${line.note?esc(line.note):'Sem observação'} · ${money(line.unitPriceCents)}</small></div><div class="line-tools"><button type="button" data-minus="${esc(line.id)}" aria-label="Diminuir ${esc(line.name)}">−</button><strong>${qty(line.quantity)}</strong><button type="button" data-plus="${esc(line.id)}" aria-label="Aumentar ${esc(line.name)}">+</button></div></div>`).join('')}</div><div id="cart-error" class="banner hidden" role="alert"></div></div><footer class="sheet-actions"><strong>${money(total)}</strong><button id="send-order" class="button primary" type="button" ${state.busy?'disabled':''}>${state.busy?'Enviando…':'Enviar para a cozinha'}</button></footer>`;}
  function openCart(){if(!state.cart.length)return;const dialog=$('#cart-dialog');$('#cart-dialog-body').innerHTML=cartDialogHtml();dialog.querySelector('[data-cart-close]').addEventListener('click',()=>dialog.close());dialog.querySelectorAll('[data-minus]').forEach(button=>button.addEventListener('click',()=>changeQty(button.dataset.minus,-1)));dialog.querySelectorAll('[data-plus]').forEach(button=>button.addEventListener('click',()=>changeQty(button.dataset.plus,1)));$('#send-order').addEventListener('click',sendOrder);dialog.showModal();}
  function rerenderOpenCart(){if($('#cart-dialog').open){$('#cart-dialog').close();if(state.cart.length)openCart();}renderCartRail();}
  function changeQty(id,delta){const line=state.cart.find(item=>item.id===id);if(!line)return;line.quantity+=delta;if(line.quantity<=0)state.cart=state.cart.filter(item=>item.id!==id);rerenderOpenCart();}
  async function sendOrder(){if(state.busy||!state.cart.length)return;state.busy=true;const button=$('#send-order');if(button){button.disabled=true;button.textContent='Enviando…';}const payload={items:state.cart.map(line=>({productId:line.productId,quantity:line.quantity,variantId:line.variantId,selections:line.selections,comboSelections:line.comboSelections,note:line.note}))};try{await request(apiPath('/orders'),{method:'POST',body:payload,mutation:true});state.cart=[];$('#cart-dialog').close();renderCartRail();toast('Pedido confirmado e enviado para a cozinha.');await refresh({quiet:true});}catch(error){const node=$('#cart-error');if(node){node.textContent=`Não foi possível enviar: ${error.message} Seu carrinho foi preservado.`;node.classList.remove('hidden');}setBanner('Há uma pendência no envio. O restante do cardápio continua disponível.');}finally{state.busy=false;if($('#cart-dialog').open)rerenderOpenCart();}}

  async function service(requestType){const button=requestType==='BILL'?$('#request-bill'):$('#call-waiter');button.disabled=true;try{await request(apiPath('/service'),{method:'POST',body:{requestType},mutation:true});toast(requestType==='BILL'?'Conta solicitada.':'Garçom chamado.');await refresh({quiet:true});}catch(error){toast(error.message);}finally{button.disabled=false;}}

  async function refresh({quiet=false}={}){try{const context=await request(apiPath());state.context=context;setBanner('');render();}catch(error){if(!quiet){$('#products').innerHTML=`<div class="empty-state"><strong>Não foi possível abrir este cardápio.</strong><p>${esc(error.message)}</p><button id="retry" class="button primary" type="button">Tentar novamente</button></div>`;$('#retry')?.addEventListener('click',()=>refresh());}else setBanner('Não foi possível atualizar a comanda agora. Você ainda pode consultar os itens já carregados.');}}

  $('#menu-search').addEventListener('input',event=>{state.query=event.target.value;$('#clear-search').classList.toggle('hidden',!state.query);renderProducts();});
  $('#clear-search').addEventListener('click',()=>{const input=$('#menu-search');state.query='';input.value='';$('#clear-search').classList.add('hidden');input.focus();renderProducts();});
  $('#review-cart').addEventListener('click',openCart);
  $('#call-waiter').addEventListener('click',()=>service('WAITER'));
  $('#request-bill').addEventListener('click',()=>service('BILL'));
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.context)void refresh({quiet:true});});
  setInterval(()=>{if(document.visibilityState==='visible'&&state.context)void refresh({quiet:true});},30000);
  refresh();
})();
