'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { validateSecretConnection, publicConnection } = require('../js/domains/fiscal/fiscal-core');
const { createDefaultFiscalProviderRegistry } = require('../js/domains/fiscal/provider-registry');
const { getActiveFiscalSidecarAuthToken } = require('./fiscal-sidecar-runtime.cjs');

const MAX_PFX_BYTES = 4 * 1024 * 1024;
function createFiscalConnectionStore({ app, safeStorage, fileName = 'pdv-fiscal-connection.enc' } = {}) {
  if (!app || typeof app.getPath !== 'function' || !safeStorage) throw new TypeError('app and safeStorage are required.');const filePath=path.join(app.getPath('userData'),fileName);
  function encryptionReady(){return typeof safeStorage.isEncryptionAvailable==='function'&&safeStorage.isEncryptionAvailable();}
  function saveSecret(input={}){if(!encryptionReady())throw new Error('Criptografia segura do sistema operacional indisponivel.');const secret=validateSecretConnection(input);const encrypted=safeStorage.encryptString(JSON.stringify(secret));fs.mkdirSync(path.dirname(filePath),{recursive:true});fs.writeFileSync(filePath,Buffer.from(encrypted).toString('base64'),{encoding:'utf8',mode:0o600});return publicConnection(secret);}
  function readSecret(){if(!fs.existsSync(filePath))return null;if(!encryptionReady())throw new Error('Criptografia segura do sistema operacional indisponivel.');const encoded=fs.readFileSync(filePath,'utf8');const decrypted=safeStorage.decryptString(Buffer.from(encoded,'base64'));return validateSecretConnection(JSON.parse(decrypted));}
  function publicStatus(){const secret=readSecret();return secret?publicConnection(secret):{configured:false};}function removeSecret(){if(fs.existsSync(filePath))fs.rmSync(filePath,{force:true});return{configured:false};}return Object.freeze({filePath,saveSecret,readSecret,publicStatus,removeSecret});
}
function createFiscalProviderResolver({store,credentialStore=null,fetchImpl=globalThis.fetch,registry=null,sidecarBaseUrlResolver=()=>null,sidecarAuthTokenResolver=getActiveFiscalSidecarAuthToken}={}){
  if(!store)throw new TypeError('Fiscal connection store is required.');if(typeof sidecarBaseUrlResolver!=='function'||typeof sidecarAuthTokenResolver!=='function')throw new TypeError('Resolvers do fiscal sidecar devem ser funcoes.');
  const providerRegistry=registry||createDefaultFiscalProviderRegistry({fetchImpl,resolveSidecarBaseUrl:sidecarBaseUrlResolver,resolveSidecarAuthToken:sidecarAuthTokenResolver});
  return async document=>{const secret=store.readSecret();if(!secret)throw new Error('Conexao fiscal nao configurada.');if(document?.provider&&document.provider!==secret.provider)throw new Error('Provedor fiscal do documento difere da configuracao ativa.');if(document?.environment&&document.environment!==secret.environment)throw new Error('Ambiente fiscal do documento difere da configuracao ativa.');if(secret.provider==='acbr-local'&&credentialStore&&typeof credentialStore.assertUsable==='function')credentialStore.assertUsable();const connection={...secret,documentType:document?.documentType||secret.documentType};return providerRegistry.create(connection,{sidecarBaseUrl:sidecarBaseUrlResolver(),sidecarAuthToken:sidecarAuthTokenResolver()});};
}
function registerFiscalIpc({ipcMain,store,credentialStore=null,isTrustedSender=null,fetchImpl=globalThis.fetch,providerResolver=null,sidecarBaseUrlResolver=()=>null,sidecarAuthTokenResolver=getActiveFiscalSidecarAuthToken,dialog=null,getParentWindow=()=>null,onCertificateSaved=null,isProductionEnabled=()=>false}={}){
  if(!ipcMain||!store)throw new TypeError('ipcMain and fiscal store are required.');const trusted=event=>typeof isTrustedSender!=='function'||Boolean(isTrustedSender(event));const resolveProvider=providerResolver||createFiscalProviderResolver({store,credentialStore,fetchImpl,sidecarBaseUrlResolver,sidecarAuthTokenResolver});const handle=(channel,fn)=>ipcMain.handle(channel,async(event,input)=>{if(!trusted(event))throw new Error('Origem IPC nao autorizada.');return fn(input||{});});
  handle('artisys:fiscal:status',()=>store.publicStatus());handle('artisys:fiscal:save',input=>store.saveSecret(input));handle('artisys:fiscal:remove',()=>store.removeSecret());handle('artisys:fiscal:certificate-status',()=>credentialStore?.publicStatus?.()||{configured:false});
  handle('artisys:fiscal:certificate-import',async input=>{if(!credentialStore||typeof credentialStore.save!=='function')throw new Error('Cofre de certificado fiscal indisponivel.');if(!dialog||typeof dialog.showOpenDialog!=='function')throw new Error('Seletor de certificado indisponivel.');const selection=await dialog.showOpenDialog(getParentWindow?.()||undefined,{title:'Selecionar certificado A1',properties:['openFile'],filters:[{name:'Certificado A1',extensions:['pfx','p12']}]});if(selection.canceled||!selection.filePaths?.[0])return{cancelled:true};const selected=selection.filePaths[0];const stat=fs.statSync(selected);if(!stat.isFile()||stat.size<=0||stat.size>MAX_PFX_BYTES)throw new Error('Certificado A1 excede o limite de 4 MiB ou e invalido.');const pfx=fs.readFileSync(selected);const status=credentialStore.save({pfxBase64:pfx.toString('base64'),password:String(input.pfxPhrase??''),csc:String(input.cscValue??''),cscId:String(input.cscId??''),certificateName:path.basename(selected)});if(typeof onCertificateSaved==='function')await onCertificateSaved(status);return status;});
  handle('artisys:fiscal:set-environment',input=>{const environment=String(input.environment||'').trim().toLowerCase();if(!['homologation','production'].includes(environment))throw new Error('Ambiente fiscal invalido.');if(environment==='production'&&!isProductionEnabled())throw new Error('Ambiente de producao ainda nao foi ativado pelo checklist fiscal.');const secret=store.readSecret();if(!secret)throw new Error('Conexao fiscal nao configurada.');return store.saveSecret({...secret,environment});});
  handle('artisys:fiscal:test',async()=>{const secret=store.readSecret();if(!secret)return{configured:false,reachable:false,error:'Conexao fiscal nao configurada.'};try{const provider=await resolveProvider({provider:secret.provider,environment:secret.environment,documentType:secret.documentType});const result=await provider.testConnection();return{...publicConnection(secret),...result};}catch(error){return{...publicConnection(secret),reachable:false,status:0,error:error?.message||String(error)};}});
  handle('artisys:fiscal:sefaz-status',async()=>{const secret=store.readSecret();if(!secret)return{configured:false,ok:false,error:'Conexao fiscal nao configurada.'};try{const provider=await resolveProvider({provider:secret.provider,environment:secret.environment,documentType:secret.documentType});if(typeof provider.sefazStatus!=='function')return{...publicConnection(secret),ok:false,error:'Provedor fiscal nao expoe status SEFAZ.'};const result=await provider.sefazStatus();return{...publicConnection(secret),...result};}catch(error){return{...publicConnection(secret),ok:false,status:0,error:error?.message||String(error)};}});
  return Object.freeze({providerResolver:resolveProvider});
}
module.exports={createFiscalConnectionStore,createFiscalProviderResolver,registerFiscalIpc};